function c(a){throw a;}var h=void 0,i=null;function aa(){return function(a){return a}}function ba(a){return function(b){this[a]=b}}function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var o,r=this;function ca(a){for(var a=a.split("."),b=r,d;d=a.shift();)if(b[d]!=i)b=b[d];else return i;return b}function da(){}
function s(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ea(a){return s(a)=="array"}function fa(a){var b=s(a);return b=="array"||b=="object"&&typeof a.length=="number"}function t(a){return typeof a=="string"}function ga(a){return typeof a=="number"}function ha(a){return s(a)=="function"}function ia(a){a=s(a);return a=="object"||a=="array"||a=="function"}function ja(a){return a[ka]||(a[ka]=++la)}var ka="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),la=0;
function ma(a,b,d){return a.call.apply(a.bind,arguments)}function na(a,b,d){a||c(Error());if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return a.apply(b,d)}}else return function(){return a.apply(b,arguments)}}function u(a,b,d){u=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ma:na;return u.apply(i,arguments)}
function pa(a,b){var d=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,d);return a.apply(this,b)}}var qa=Date.now||function(){return+new Date};function v(a,b){function d(){}d.prototype=b.prototype;a.i=b.prototype;a.prototype=new d};function ra(a,b){for(var d=1;d<arguments.length;d++)var e=String(arguments[d]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,e);return a}function sa(a){return!/[^\t\n\r ]/.test(a)}function ta(a){return!/[^0-9]/.test(a)}function ua(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")}
function va(a){if(!wa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(xa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ya,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(za,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(Aa,"&quot;"));return a}var xa=/&/g,ya=/</g,za=/>/g,Aa=/\"/g,wa=/[&<>\"]/;function Ba(a){return ua(a.replace(/  /g," &#160;"),h)}var Ca={"\000":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},Da={"'":"\\'"};
function Ea(a){var n;a=String(a);if(a.quote)return a.quote();else{for(var b=['"'],d=0;d<a.length;d++){var e=a.charAt(d),f=e.charCodeAt(0),g=b,j=d+1,k;if(!(k=Ca[e])){if(!(f>31&&f<127))if(e in Da)e=Da[e];else if(e in Ca)n=Da[e]=Ca[e],e=n;else{f=e;k=e.charCodeAt(0);if(k>31&&k<127)f=e;else{if(k<256){if(f="\\x",k<16||k>256)f+="0"}else f="\\u",k<4096&&(f+="0");f+=k.toString(16).toUpperCase()}e=Da[e]=f}k=e}g[j]=k}b.push('"');return b.join("")}}function Fa(a,b){return a.indexOf(b)!=-1}
function Ga(a,b){for(var d=0,e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(e.length,f.length),j=0;d==0&&j<g;j++){var k=e[j]||"",n=f[j]||"",p=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var w=p.exec(k)||["","",""],D=q.exec(n)||["","",""];if(w[0].length==0&&D[0].length==0)break;d=Ha(w[1].length==0?0:parseInt(w[1],10),D[1].length==0?0:parseInt(D[1],10))||Ha(w[2].length==0,D[2].length==0)||Ha(w[2],D[2])}while(d==
0)}return d}function Ha(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}function Ja(a){for(var b=0,d=0;d<a.length;++d)b=31*b+a.charCodeAt(d),b%=4294967296;return b};var Ka,La,Ma,Na,Oa,Pa,Qa,Ra=(Qa="ScriptEngine"in r&&r.ScriptEngine()=="JScript")?r.ScriptEngineMajorVersion()+"."+r.ScriptEngineMinorVersion()+"."+r.ScriptEngineBuildVersion():"0";function Sa(a,b){this.w=Qa?[]:"";a!=i&&this.append.apply(this,arguments)}Sa.prototype.set=function(a){this.clear();this.append(a)};Qa?(Sa.prototype.ab=0,Sa.prototype.append=function(a,b,d){b==i?this.w[this.ab++]=a:(this.w.push.apply(this.w,arguments),this.ab=this.w.length);return this}):Sa.prototype.append=function(a,b,d){this.w+=a;if(b!=i)for(var e=1;e<arguments.length;e++)this.w+=arguments[e];return this};Sa.prototype.clear=function(){Qa?this.ab=this.w.length=0:this.w=""};
Sa.prototype.toString=function(){if(Qa){var a=this.w.join("");this.clear();a&&this.append(a);return a}else return this.w};function x(a,b){this.x=a!==h?a:0;this.y=b!==h?b:0}x.prototype.N=function(){return new x(this.x,this.y)};x.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function Ta(a,b){return new x(a.x-b.x,a.y-b.y)};function Ua(a,b,d,e){this.top=a;this.right=b;this.bottom=d;this.left=e}Ua.prototype.N=function(){return new Ua(this.top,this.right,this.bottom,this.left)};Ua.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};Ua.prototype.contains=function(a){return!this||!a?!1:a instanceof Ua?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};function Va(a){this.stack=Error().stack||"";if(a)this.message=String(a)}v(Va,Error);Va.prototype.name="CustomError";function Wa(a,b){b.unshift(a);Va.call(this,ra.apply(i,b));b.shift();this.xd=a}v(Wa,Va);Wa.prototype.name="AssertionError";function Xa(a,b){c(new Wa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};var Ya=Array.prototype,Za=Ya.indexOf?function(a,b,d){return Ya.indexOf.call(a,b,d)}:function(a,b,d){d=d==i?0:d<0?Math.max(0,a.length+d):d;if(t(a))return!t(b)||b.length!=1?-1:a.indexOf(b,d);for(;d<a.length;d++)if(d in a&&a[d]===b)return d;return-1},$a=Ya.forEach?function(a,b,d){Ya.forEach.call(a,b,d)}:function(a,b,d){for(var e=a.length,f=t(a)?a.split(""):a,g=0;g<e;g++)g in f&&b.call(d,f[g],g,a)};function ab(a,b){var d=Za(a,b);d>=0&&Ya.splice.call(a,d,1)}
function bb(a){return Ya.concat.apply(Ya,arguments)}function cb(a){if(ea(a))return bb(a);else{for(var b=[],d=0,e=a.length;d<e;d++)b[d]=a[d];return b}}function db(a,b,d,e){Ya.splice.apply(a,eb(arguments,1))}function eb(a,b,d){return arguments.length<=2?Ya.slice.call(a,b):Ya.slice.call(a,b,d)}function fb(a,b){Ya.sort.call(a,b||gb)}
function hb(a,b){for(var d=0;d<a.length;d++)a[d]={index:d,value:a[d]};var e=b||gb;fb(a,function(a,b){return e(a.value,b.value)||a.index-b.index});for(d=0;d<a.length;d++)a[d]=a[d].value}function gb(a,b){return a>b?1:a<b?-1:0};function ib(){return r.navigator?r.navigator.userAgent:i}function jb(){return r.navigator}Oa=Na=Ma=La=Ka=!1;var kb;if(kb=ib()){var lb=jb();Ka=kb.indexOf("Opera")==0;La=!Ka&&kb.indexOf("MSIE")!=-1;Na=(Ma=!Ka&&kb.indexOf("WebKit")!=-1)&&kb.indexOf("Mobile")!=-1;Oa=!Ka&&!Ma&&lb.product=="Gecko"}var mb=Ka,y=La,nb=Oa,z=Ma,pb=Na,qb=jb();Pa=Fa(qb&&qb.platform||"","Mac");var rb=!!jb()&&Fa(jb().appVersion||"","X11"),sb;
a:{var tb="",ub;if(mb&&r.opera)var vb=r.opera.version,tb=typeof vb=="function"?vb():vb;else if(nb?ub=/rv\:([^\);]+)(\)|;)/:y?ub=/MSIE\s+([^\);]+)(\)|;)/:z&&(ub=/WebKit\/(\S+)/),ub)var wb=ub.exec(ib()),tb=wb?wb[1]:"";if(y){var xb,yb=r.document;xb=yb?yb.documentMode:h;if(xb>parseFloat(tb)){sb=String(xb);break a}}sb=tb}var zb={};function Ab(a){return zb[a]||(zb[a]=Ga(sb,a)>=0)}var Bb={};function Cb(){return Bb[9]||(Bb[9]=y&&document.documentMode&&document.documentMode>=9)};var Db,Eb=!y||Cb();!nb&&!y||y&&Cb()||nb&&Ab("1.9.1");y&&Ab("9");function Fb(a,b){a.className=b}function Gb(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function Hb(a,b){var d=Gb(a),e=eb(arguments,1),f;f=d;for(var g=0,j=0;j<e.length;j++)Za(f,e[j])>=0||(f.push(e[j]),g++);f=g==e.length;a.className=d.join(" ");return f}function Ib(a,b){for(var d=Gb(a),e=eb(arguments,1),f=d,g=0,j=0;j<f.length;j++)Za(e,f[j])>=0&&(db(f,j--,1),g++);a.className=d.join(" ")};function Jb(a,b){this.width=a;this.height=b}Jb.prototype.N=function(){return new Jb(this.width,this.height)};Jb.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};Jb.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Jb.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Kb(a,b,d){for(var e in a)b.call(d,a[e],e,a)}function Lb(a){var b=[],d=0,e;for(e in a)b[d++]=a[e];return b}function Mb(){var a=Nb,b;for(b in a)return!1;return!0}function Ob(a){var b={},d;for(d in a)b[d]=a[d];return b}var Pb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function Qb(a,b){for(var d,e,f=1;f<arguments.length;f++){e=arguments[f];for(d in e)a[d]=e[d];for(var g=0;g<Pb.length;g++)d=Pb[g],Object.prototype.hasOwnProperty.call(e,d)&&(a[d]=e[d])}};function A(a){return a?new Rb(B(a)):Db||(Db=new Rb)}function Sb(a){return t(a)?document.getElementById(a):a}function Tb(a,b){var d=b&&b!="*"?b.toUpperCase():"";return a.querySelectorAll&&a.querySelector&&(!z||Ub(document)||Ab("528"))&&d?a.querySelectorAll(d+""):a.getElementsByTagName(d||"*")}function Vb(a,b){Kb(b,function(b,e){e=="style"?a.style.cssText=b:e=="class"?a.className=b:e=="for"?a.htmlFor=b:e in Wb?a.setAttribute(Wb[e],b):e.lastIndexOf("aria-",0)==0?a.setAttribute(e,b):a[e]=b})}
var Wb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};function Xb(a,b,d){return Yb(document,arguments)}
function Yb(a,b){var d=b[0],e=b[1];if(!Eb&&e&&(e.name||e.type)){d=["<",d];e.name&&d.push(' name="',va(e.name),'"');if(e.type){d.push(' type="',va(e.type),'"');var f={};Qb(f,e);e=f;delete e.type}d.push(">");d=d.join("")}d=a.createElement(d);if(e)t(e)?d.className=e:ea(e)?Hb.apply(i,[d].concat(e)):Vb(d,e);b.length>2&&Zb(a,d,b,2);return d}
function Zb(a,b,d,e){function f(d){d&&b.appendChild(t(d)?a.createTextNode(d):d)}for(;e<d.length;e++){var g=d[e];fa(g)&&!(ia(g)&&g.nodeType>0)?$a($b(g)?cb(g):g,f):f(g)}}function ac(a){return document.createElement(a)}function Ub(a){return a.compatMode=="CSS1Compat"}function bc(a,b){a.appendChild(b)}function cc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function dc(a){a&&a.parentNode&&a.parentNode.removeChild(a)}
function ec(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function B(a){return a.nodeType==9?a:a.ownerDocument||a.document}
function fc(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else cc(a),a.appendChild(B(a).createTextNode(b))}function $b(a){if(a&&typeof a.length=="number")if(ia(a))return typeof a.item=="function"||typeof a.item=="string";else if(ha(a))return typeof a.item=="function";return!1}function Rb(a){this.g=a||r.document||document}o=Rb.prototype;o.lb=A;
o.a=function(a){return t(a)?this.g.getElementById(a):a};o.ja=function(a,b,d){return Yb(this.g,arguments)};o.createElement=function(a){return this.g.createElement(a)};o.createTextNode=function(a){return this.g.createTextNode(a)};function gc(a){var b=a.g,a=!z&&Ub(b)?b.documentElement:b.body,b=b.parentWindow||b.defaultView;return new x(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}o.appendChild=bc;o.append=function(a,b){Zb(B(a),a,arguments,1)};o.contains=ec;function hc(a,b,d,e){this.left=a;this.top=b;this.width=d;this.height=e}hc.prototype.N=function(){return new hc(this.left,this.top,this.width,this.height)};hc.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
hc.prototype.Yb=function(a){var b=Math.max(this.left,a.left),d=Math.min(this.left+this.width,a.left+a.width);if(b<=d){var e=Math.max(this.top,a.top),a=Math.min(this.top+this.height,a.top+a.height);if(e<=a)return this.left=b,this.top=e,this.width=d-b,this.height=a-e,!0}return!1};
hc.prototype.contains=function(a){return a instanceof hc?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};function ic(a,b){var d=B(a);return d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,i))?d[b]||d.getPropertyValue(b):""}function jc(a,b){return ic(a,b)||(a.currentStyle?a.currentStyle[b]:i)||a.style[b]}function kc(a){var a=a?a.nodeType==9?a:B(a):document,b;if(b=y)if(b=!Cb())b=A(a),b=!Ub(b.g);return b?a.body:a.documentElement}
function lc(a){var b=a.getBoundingClientRect();if(y)a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop;return b}
function mc(a){if(y)return a.offsetParent;for(var b=B(a),d=jc(a,"position"),e=d=="fixed"||d=="absolute",a=a.parentNode;a&&a!=b;a=a.parentNode)if(d=jc(a,"position"),e=e&&d=="static"&&a!=b.documentElement&&a!=b.body,!e&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||d=="fixed"||d=="absolute"||d=="relative"))return a;return i}
function nc(a){for(var b=new Ua(0,Infinity,Infinity,0),d=A(a),e=d.g.body,f=!z&&Ub(d.g)?d.g.documentElement:d.g.body,g;a=mc(a);)if((!y||a.clientWidth!=0)&&(!z||a.clientHeight!=0||a!=e)&&(a.scrollWidth!=a.clientWidth||a.scrollHeight!=a.clientHeight)&&jc(a,"overflow")!="visible"){var j=oc(a),k;k=a;if(nb&&!Ab("1.9")){var n=parseFloat(ic(k,"borderLeftWidth"));if(pc(k)){var p=k.offsetWidth-k.clientWidth-n-parseFloat(ic(k,"borderRightWidth"));n+=p}k=new x(n,parseFloat(ic(k,"borderTopWidth")))}else k=new x(k.clientLeft,
k.clientTop);j.x+=k.x;j.y+=k.y;b.top=Math.max(b.top,j.y);b.right=Math.min(b.right,j.x+a.clientWidth);b.bottom=Math.min(b.bottom,j.y+a.clientHeight);b.left=Math.max(b.left,j.x);g=g||a!=f}e=f.scrollLeft;f=f.scrollTop;z?(b.left+=e,b.top+=f):(b.left=Math.max(b.left,e),b.top=Math.max(b.top,f));if(!g||z)b.right+=e,b.bottom+=f;d=d.g.parentWindow||d.g.defaultView||window;g=d.document;z&&!Ab("500")&&!pb?(typeof d.innerHeight=="undefined"&&(d=window),g=d.innerHeight,a=d.document.documentElement.scrollHeight,
d==d.top&&a<g&&(g-=15),d=new Jb(d.innerWidth,g)):(d=Ub(g)?g.documentElement:g.body,d=new Jb(d.clientWidth,d.clientHeight));b.right=Math.min(b.right,e+d.width);b.bottom=Math.min(b.bottom,f+d.height);return b.top>=0&&b.left>=0&&b.bottom>b.top&&b.right>b.left?b:i}
function oc(a){var b,d=B(a),e=jc(a,"position"),f=nb&&d.getBoxObjectFor&&!a.getBoundingClientRect&&e=="absolute"&&(b=d.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),g=new x(0,0),j=kc(d);if(a==j)return g;if(a.getBoundingClientRect)b=lc(a),a=gc(A(d)),g.x=b.left+a.x,g.y=b.top+a.y;else if(d.getBoxObjectFor&&!f)b=d.getBoxObjectFor(a),a=d.getBoxObjectFor(j),g.x=b.screenX-a.screenX,g.y=b.screenY-a.screenY;else{b=a;do{g.x+=b.offsetLeft;g.y+=b.offsetTop;b!=a&&(g.x+=b.clientLeft||0,g.y+=b.clientTop||0);if(z&&
jc(b,"position")=="fixed"){g.x+=d.body.scrollLeft;g.y+=d.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(mb||z&&e=="absolute")g.y-=d.body.offsetTop;for(b=a;(b=mc(b))&&b!=d.body&&b!=j;)if(g.x-=b.scrollLeft,!mb||b.tagName!="TR")g.y-=b.scrollTop}return g}function qc(a,b){typeof a=="number"&&(a=(b?Math.round(a):a)+"px");return a}
function rc(a){if(jc(a,"display")!="none")return sc(a);var b=a.style,d=b.display,e=b.visibility,f=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=sc(a);b.display=d;b.position=f;b.visibility=e;return a}function sc(a){var b=a.offsetWidth,d=a.offsetHeight,e=z&&!b&&!d;return(b===h||e)&&a.getBoundingClientRect?(a=lc(a),new Jb(a.right-a.left,a.bottom-a.top)):new Jb(b,d)}function tc(a,b){a.style.display=b?"":"none"}
function uc(a){y?a.cssText=".dbg-sev{color:#F00}.dbg-w{color:#C40}.dbg-sh{font-weight:bold;color:#000}.dbg-i{color:#444}.dbg-f{color:#999}.dbg-ev{color:#0A0}.dbg-m{color:#990}.logmsg{border-bottom:1px solid #CCC;padding:2px}.logsep{background-color: #8C8;}.logdiv{border:1px solid #CCC;background-color:#FCFCFC;font:medium monospace}":a[z?"innerText":"innerHTML"]=".dbg-sev{color:#F00}.dbg-w{color:#C40}.dbg-sh{font-weight:bold;color:#000}.dbg-i{color:#444}.dbg-f{color:#999}.dbg-ev{color:#0A0}.dbg-m{color:#990}.logmsg{border-bottom:1px solid #CCC;padding:2px}.logsep{background-color: #8C8;}.logdiv{border:1px solid #CCC;background-color:#FCFCFC;font:medium monospace}"}
function pc(a){return"rtl"==jc(a,"direction")};function vc(a,b,d,e,f,g,j,k){var n,p=d.offsetParent;if(p){var q=p.tagName=="HTML"||p.tagName=="BODY";if(!q||jc(p,"position")!="static")n=oc(p),q||(n=Ta(n,new x(p.scrollLeft,p.scrollTop)))}p=oc(a);q=rc(a);p=new hc(p.x,p.y,q.width,q.height);(q=nc(a))&&p.Yb(new hc(q.left,q.top,q.right-q.left,q.bottom-q.top));var q=A(a),w=A(d);if(q.g!=w.g){var D=q.g.body,w=w.g.parentWindow||w.g.defaultView,R=new x(0,0),ob=B(D)?B(D).parentWindow||B(D).defaultView:window,Od=D;do{var oa;if(ob==w)oa=oc(Od);else{var M=Od;
oa=new x;if(M.nodeType==1)if(M.getBoundingClientRect)M=lc(M),oa.x=M.left,oa.y=M.top;else{var Kc=gc(A(M)),M=oc(M);oa.x=M.x-Kc.x;oa.y=M.y-Kc.y}else{var Kc=ha(M.Dc),Lc=M;M.targetTouches?Lc=M.targetTouches[0]:Kc&&M.Q.targetTouches&&(Lc=M.Q.targetTouches[0]);oa.x=Lc.clientX;oa.y=Lc.clientY}}R.x+=oa.x;R.y+=oa.y}while(ob&&ob!=w&&(Od=ob.frameElement)&&(ob=ob.parent));D=Ta(R,oc(D));y&&!Ub(q.g)&&(D=Ta(D,gc(q)));p.left+=D.x;p.top+=D.y}a=(b&4&&pc(a)?b^2:b)&-5;b=new x(a&2?p.left+p.width:p.left,a&1?p.top+p.height:
p.top);n&&(b=Ta(b,n));f&&(b.x+=(a&2?-1:1)*f.x,b.y+=(a&1?-1:1)*f.y);var Ia;if(j&&(Ia=nc(d))&&n)Ia.top=Math.max(0,Ia.top-n.y),Ia.right-=n.x,Ia.bottom-=n.y,Ia.left=Math.max(0,Ia.left-n.x);return wc(b,d,e,g,Ia,j,k)}
function wc(a,b,d,e,f,g,j){var a=a.N(),k=0,n=(d&4&&pc(b)?d^2:d)&-5,d=rc(b),j=j?j.N():d.N();if(e||n!=0)n&2?a.x-=j.width+(e?e.right:0):e&&(a.x+=e.left),n&1?a.y-=j.height+(e?e.bottom:0):e&&(a.y+=e.top);if(g){if(f){k=a;e=0;if((g&65)==65&&(k.x<f.left||k.x>=f.right))g&=-2;if((g&132)==132&&(k.y<f.top||k.y>=f.bottom))g&=-5;if(k.x<f.left&&g&1)k.x=f.left,e|=1;k.x<f.left&&k.x+j.width>f.right&&g&16&&(j.width-=k.x+j.width-f.right,e|=4);if(k.x+j.width>f.right&&g&1)k.x=Math.max(f.right-j.width,f.left),e|=1;g&2&&
(e|=(k.x<f.left?16:0)|(k.x+j.width>f.right?32:0));if(k.y<f.top&&g&4)k.y=f.top,e|=2;k.y>=f.top&&k.y+j.height>f.bottom&&g&32&&(j.height-=k.y+j.height-f.bottom,e|=8);if(k.y+j.height>f.bottom&&g&4)k.y=Math.max(f.bottom-j.height,f.top),e|=2;g&8&&(e|=(k.y<f.top?64:0)|(k.y+j.height>f.bottom?128:0));k=e}else k=256;if(k&496)return k}g=a;f=nb&&(Pa||rb)&&Ab("1.9");g instanceof x?(a=g.x,g=g.y):(a=g,g=h);b.style.left=qc(a,f);b.style.top=qc(g,f);if(!(d==j||(!d||!j?0:d.width==j.width&&d.height==j.height))){var d=
j,p;d instanceof Jb?(p=d.height,d=d.width):c(Error("missing height argument"));b.style.width=qc(d,!0);b.style.height=qc(p,!0)}return k};function xc(){}xc.prototype.G=function(){};function yc(a,b){this.element=a;this.Hb=b}v(yc,xc);yc.prototype.G=function(a,b,d){vc(this.element,this.Hb,a,b,h,d)};var zc;function Ac(){}Ac.prototype.Kb=!1;Ac.prototype.B=function(){if(!this.Kb)this.Kb=!0,this.f()};Ac.prototype.f=function(){this.yc&&Bc.apply(i,this.yc)};function Cc(a){a&&typeof a.B=="function"&&a.B()}function Bc(a){for(var b=0,d=arguments.length;b<d;++b){var e=arguments[b];fa(e)?Bc.apply(i,e):Cc(e)}};!y||Cb();var Dc=y&&!Ab("8");function C(a,b){this.type=a;this.currentTarget=this.target=b}v(C,Ac);o=C.prototype;o.f=function(){delete this.type;delete this.target;delete this.currentTarget};o.ca=!1;o.Fa=!0;o.stopPropagation=function(){this.ca=!0};o.preventDefault=function(){this.Fa=!1};var Ec="click",Fc="keydown";var Gc=new Function("a","return a");function Hc(a,b){a&&this.Sa(a,b)}v(Hc,C);o=Hc.prototype;o.target=i;o.relatedTarget=i;o.offsetX=0;o.offsetY=0;o.clientX=0;o.clientY=0;o.screenX=0;o.screenY=0;o.button=0;o.keyCode=0;o.charCode=0;o.ctrlKey=!1;o.altKey=!1;o.shiftKey=!1;o.metaKey=!1;o.dd=!1;o.Q=i;
o.Sa=function(a,b){var d=this.type=a.type;C.call(this,d);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;if(e){if(nb){var f;a:{try{Gc(e.nodeName);f=!0;break a}catch(g){}f=!1}f||(e=i)}}else if(d=="mouseover")e=a.fromElement;else if(d=="mouseout")e=a.toElement;this.relatedTarget=e;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(d=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.dd=Pa?a.metaKey:a.ctrlKey;this.state=a.state;this.Q=a;delete this.Fa;delete this.ca};o.stopPropagation=function(){Hc.i.stopPropagation.call(this);this.Q.stopPropagation?this.Q.stopPropagation():this.Q.cancelBubble=!0};
o.preventDefault=function(){Hc.i.preventDefault.call(this);var a=this.Q;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Dc)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};o.Dc=l("Q");o.f=function(){Hc.i.f.call(this);this.relatedTarget=this.currentTarget=this.target=this.Q=i};function Ic(){}var Jc=0;o=Ic.prototype;o.key=0;o.da=!1;o.bb=!1;o.Sa=function(a,b,d,e,f,g){ha(a)?this.$b=!0:a&&a.handleEvent&&ha(a.handleEvent)?this.$b=!1:c(Error("Invalid listener argument"));this.qa=a;this.jc=b;this.src=d;this.type=e;this.capture=!!f;this.Qa=g;this.bb=!1;this.key=++Jc;this.da=!1};o.handleEvent=function(a){return this.$b?this.qa.call(this.Qa||this.src,a):this.qa.handleEvent.call(this.qa,a)};function Mc(a,b){this.bc=b;this.ba=[];a>this.bc&&c(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<a;d++)this.ba.push(this.O?this.O():{})}v(Mc,Ac);Mc.prototype.O=i;Mc.prototype.Jb=i;Mc.prototype.getObject=function(){return this.ba.length?this.ba.pop():this.O?this.O():{}};function Nc(a,b){a.ba.length<a.bc?a.ba.push(b):Oc(a,b)}function Oc(a,b){if(a.Jb)a.Jb(b);else if(ia(b))if(ha(b.B))b.B();else for(var d in b)delete b[d]}
Mc.prototype.f=function(){Mc.i.f.call(this);for(var a=this.ba;a.length;)Oc(this,a.pop());delete this.ba};var Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc;
(function(){function a(){return{j:0,t:0}}function b(){return[]}function d(){function a(b){b=j.call(a.src,a.key,b);if(!b)return b}return a}function e(){return new Ic}function f(){return new Hc}var g=Qa&&!(Ga(Ra,"5.7")>=0),j;Uc=function(a){j=a};if(g){Pc=function(){return k.getObject()};Qc=function(a){Nc(k,a)};Rc=function(){return n.getObject()};Sc=function(a){Nc(n,a)};Tc=function(){return p.getObject()};Vc=function(){Nc(p,d())};Wc=function(){return q.getObject()};Xc=function(a){Nc(q,a)};Yc=function(){return w.getObject()};
Zc=function(a){Nc(w,a)};var k=new Mc(0,600);k.O=a;var n=new Mc(0,600);n.O=b;var p=new Mc(0,600);p.O=d;var q=new Mc(0,600);q.O=e;var w=new Mc(0,600);w.O=f}else Pc=a,Qc=da,Rc=b,Sc=da,Tc=d,Vc=da,Wc=e,Xc=da,Yc=f,Zc=da})();var $c={},E={},ad={},bd={};
function F(a,b,d,e,f){if(b)if(ea(b)){for(var g=0;g<b.length;g++)F(a,b[g],d,e,f);return i}else{var e=!!e,j=E;b in j||(j[b]=Pc());j=j[b];e in j||(j[e]=Pc(),j.j++);var j=j[e],k=ja(a),n;j.t++;if(j[k]){n=j[k];for(g=0;g<n.length;g++)if(j=n[g],j.qa==d&&j.Qa==f){if(j.da)break;return n[g].key}}else n=j[k]=Rc(),j.j++;g=Tc();g.src=a;j=Wc();j.Sa(d,g,a,b,e,f);d=j.key;g.key=d;n.push(j);$c[d]=j;ad[k]||(ad[k]=Rc());ad[k].push(j);a.addEventListener?(a==r||!a.Ib)&&a.addEventListener(b,g,e):a.attachEvent(b in bd?bd[b]:
bd[b]="on"+b,g);return d}else c(Error("Invalid event type"))}function cd(a,b,d,e,f){if(ea(b))for(var g=0;g<b.length;g++)cd(a,b[g],d,e,f);else a=F(a,b,d,e,f),$c[a].bb=!0}function dd(a,b,d,e,f){if(ea(b))for(var g=0;g<b.length;g++)dd(a,b[g],d,e,f);else if(e=!!e,a=ed(a,b,e))for(g=0;g<a.length;g++)if(a[g].qa==d&&a[g].capture==e&&a[g].Qa==f){fd(a[g].key);break}}
function fd(a){if(!$c[a])return!1;var b=$c[a];if(b.da)return!1;var d=b.src,e=b.type,f=b.jc,g=b.capture;d.removeEventListener?(d==r||!d.Ib)&&d.removeEventListener(e,f,g):d.detachEvent&&d.detachEvent(e in bd?bd[e]:bd[e]="on"+e,f);d=ja(d);f=E[e][g][d];if(ad[d]){var j=ad[d];ab(j,b);j.length==0&&delete ad[d]}b.da=!0;f.ec=!0;gd(e,g,d,f);delete $c[a];return!0}
function gd(a,b,d,e){if(!e.Ta&&e.ec){for(var f=0,g=0;f<e.length;f++)if(e[f].da){var j=e[f].jc;j.src=i;Vc(j);Xc(e[f])}else f!=g&&(e[g]=e[f]),g++;e.length=g;e.ec=!1;g==0&&(Sc(e),delete E[a][b][d],E[a][b].j--,E[a][b].j==0&&(Qc(E[a][b]),delete E[a][b],E[a].j--),E[a].j==0&&(Qc(E[a]),delete E[a]))}}
function hd(a){var b,d=0,e=b==i;b=!!b;if(a==i)Kb(ad,function(a){for(var g=a.length-1;g>=0;g--){var f=a[g];if(e||b==f.capture)fd(f.key),d++}});else if(a=ja(a),ad[a])for(var a=ad[a],f=a.length-1;f>=0;f--){var g=a[f];if(e||b==g.capture)fd(g.key),d++}}function ed(a,b,d){var e=E;return b in e&&(e=e[b],d in e&&(e=e[d],a=ja(a),e[a]))?e[a]:i}
function id(a,b,d,e,f){var g=1,b=ja(b);if(a[b]){a.t--;a=a[b];a.Ta?a.Ta++:a.Ta=1;try{for(var j=a.length,k=0;k<j;k++){var n=a[k];n&&!n.da&&(g&=jd(n,f)!==!1)}}finally{a.Ta--,gd(d,e,b,a)}}return Boolean(g)}function jd(a,b){var d=a.handleEvent(b);a.bb&&fd(a.key);return d}
Uc(function(a,b){if(!$c[a])return!0;var d=$c[a],e=d.type,f=E;if(!(e in f))return!0;var f=f[e],g,j;zc===h&&(zc=y&&!r.addEventListener);if(zc){g=b||ca("window.event");var k=!0 in f,n=!1 in f;if(k){if(g.keyCode<0||g.returnValue!=h)return!0;a:{var p=!1;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(q){p=!0}if(p||g.returnValue==h)g.returnValue=!0}}p=Yc();p.Sa(g,this);g=!0;try{if(k){for(var w=Rc(),D=p.currentTarget;D;D=D.parentNode)w.push(D);j=f[!0];j.t=j.j;for(var R=w.length-1;!p.ca&&R>=0&&j.t;R--)p.currentTarget=
w[R],g&=id(j,w[R],e,!0,p);if(n){j=f[!1];j.t=j.j;for(R=0;!p.ca&&R<w.length&&j.t;R++)p.currentTarget=w[R],g&=id(j,w[R],e,!1,p)}}else g=jd(d,p)}finally{if(w)w.length=0,Sc(w);p.B();Zc(p)}return g}e=new Hc(b,this);try{g=jd(d,e)}finally{e.B()}return g});var kd=0;function ld(a){this.q=a;this.h=[]}v(ld,Ac);var md=[];function G(a,b,d,e,f){ea(d)||(md[0]=d,d=md);for(var g=0;g<d.length;g++)a.h.push(F(b,d[g],e||a,f||!1,a.q||a))}function nd(a,b,d,e,f,g){if(ea(d))for(var j=0;j<d.length;j++)nd(a,b,d[j],e,f,g);else{a:{e=e||a;g=g||a.q||a;f=!!f;if(b=ed(b,d,f))for(d=0;d<b.length;d++)if(!b[d].da&&b[d].qa==e&&b[d].capture==f&&b[d].Qa==g){b=b[d];break a}b=i}if(b)b=b.key,fd(b),ab(a.h,b)}}ld.prototype.Wa=function(){$a(this.h,fd);this.h.length=0};
ld.prototype.f=function(){ld.i.f.call(this);this.Wa()};ld.prototype.handleEvent=function(){c(Error("EventHandler.handleEvent not implemented"))};function od(a,b){this.gb=a instanceof x?a:new x(a,b)}v(od,xc);od.prototype.G=function(a,b,d,e){vc(kc(a),0,a,b,this.gb,d,i,e)};function pd(){}v(pd,Ac);o=pd.prototype;o.Ib=!0;o.Va=i;o.xb=ba("Va");o.addEventListener=function(a,b,d,e){F(this,a,b,d,e)};o.removeEventListener=function(a,b,d,e){dd(this,a,b,d,e)};
o.dispatchEvent=function(a){var b=a.type||a,d=E;if(b in d){if(t(a))a=new C(a,this);else if(a instanceof C)a.target=a.target||this;else{var e=a,a=new C(b,this);Qb(a,e)}var e=1,f,d=d[b],b=!0 in d,g;if(b){f=[];for(g=this;g;g=g.Va)f.push(g);g=d[!0];g.t=g.j;for(var j=f.length-1;!a.ca&&j>=0&&g.t;j--)a.currentTarget=f[j],e&=id(g,f[j],a.type,!0,a)&&a.Fa!=!1}if(!1 in d)if(g=d[!1],g.t=g.j,b)for(j=0;!a.ca&&j<f.length&&g.t;j++)a.currentTarget=f[j],e&=id(g,f[j],a.type,!1,a)&&a.Fa!=!1;else for(f=this;!a.ca&&f&&
g.t;f=f.Va)a.currentTarget=f,e&=id(g,f,a.type,!1,a)&&a.Fa!=!1;a=Boolean(e)}else a=!0;return a};o.f=function(){pd.i.f.call(this);hd(this);this.Va=i};var qd=r.window;function rd(a,b,d){ha(a)?d&&(a=u(a,d)):a&&typeof a.handleEvent=="function"?a=u(a.handleEvent,a):c(Error("Invalid listener argument"));return b>2147483647?-1:qd.setTimeout(a,b||0)};function sd(a,b){this.q=new ld(this);this.vb(a||i);if(b)this.ta=b}v(sd,pd);o=sd.prototype;o.b=i;o.tc=!0;o.Ab=i;o.p=!1;o.md=!1;o.ob=-1;o.ac=-1;o.Lc=!1;o.Ac=!0;o.ta="toggle_display";o.a=l("b");o.vb=function(a){this.p&&c(Error("Can not change this state of the popup while showing."));this.b=a};
function td(a,b){a.Ga&&a.Ga.stop();a.Da&&a.Da.stop();if(b){if(!a.p&&a.qb()){a.b||c(Error("Caller must call setElement before trying to show the popup"));a.G();var d=B(a.b);a.Lc&&G(a.q,d,Fc,a.Yc,!0);if(a.tc)if(G(a.q,d,"mousedown",a.gc,!0),y){var e;try{e=d.activeElement}catch(f){}for(;e&&e.nodeName=="IFRAME";){try{var g=z?e.document||e.contentWindow.document:e.contentDocument||e.contentWindow.document}catch(j){break}d=g;e=d.activeElement}G(a.q,d,"mousedown",a.gc,!0);G(a.q,d,"deactivate",a.fc)}else G(a.q,
d,"blur",a.fc);a.ta=="toggle_display"?(a.b.style.visibility="visible",tc(a.b,!0)):a.ta=="move_offscreen"&&a.G();a.p=!0;a.Ga?(cd(a.Ga,"end",a.hc,!1,a),a.Ga.play()):a.hc()}}else ud(a)}o.G=da;function ud(a,b){if(!a.p||!a.dispatchEvent({type:"beforehide",target:b}))return!1;a.q&&a.q.Wa();a.Da?(cd(a.Da,"end",pa(a.Gb,b),!1,a),a.Da.play()):a.Gb(b);return!0}
o.Gb=function(a){if(this.ta=="toggle_display")this.md?rd(this.Vb,0,this):this.Vb();else if(this.ta=="move_offscreen")this.b.style.left="-200px",this.b.style.top="-200px";this.p=!1;this.rb(a)};o.Vb=function(){this.b.style.visibility="hidden";tc(this.b,!1)};o.qb=function(){return this.dispatchEvent("beforeshow")};o.hc=function(){this.ob=qa();this.ac=-1;this.dispatchEvent("show")};o.rb=function(a){this.ac=qa();this.dispatchEvent({type:"hide",target:a})};
o.gc=function(a){a=a.target;!ec(this.b,a)&&(!this.Ab||ec(this.Ab,a))&&!(qa()-this.ob<150)&&ud(this,a)};o.Yc=function(a){a.keyCode==27&&ud(this,a.target)&&(a.preventDefault(),a.stopPropagation())};o.fc=function(a){if(this.Ac){var b=B(this.b);if(y||mb){if(a=b.activeElement,!a||ec(this.b,a))return}else if(a.target!=b)return;qa()-this.ob<150||ud(this)}};o.f=function(){sd.i.f.call(this);this.q.B();Cc(this.Ga);Cc(this.Da);delete this.b;delete this.q};function vd(a,b){this.ed=4;this.sb=b||h;sd.call(this,a)}v(vd,sd);vd.prototype.G=function(){if(this.sb){var a=!this.p&&this.ta!="move_offscreen",b=this.a();if(a)b.style.visibility="hidden",tc(b,!0);this.sb.G(b,this.ed,this.wd);a&&tc(b,!1)}};function wd(a){if(typeof a.la=="function")return a.la();if(t(a))return a.split("");if(fa(a)){for(var b=[],d=a.length,e=0;e<d;e++)b.push(a[e]);return b}return Lb(a)};function xd(a,b){this.k={};this.h=[];var d=arguments.length;if(d>1){d%2&&c(Error("Uneven number of arguments"));for(var e=0;e<d;e+=2)this.set(arguments[e],arguments[e+1])}else a&&this.$a(a)}o=xd.prototype;o.j=0;o.yb=0;o.la=function(){yd(this);for(var a=[],b=0;b<this.h.length;b++)a.push(this.k[this.h[b]]);return a};o.clear=function(){this.k={};this.yb=this.j=this.h.length=0};o.remove=function(a){return zd(this.k,a)?(delete this.k[a],this.j--,this.yb++,this.h.length>2*this.j&&yd(this),!0):!1};
function yd(a){if(a.j!=a.h.length){for(var b=0,d=0;b<a.h.length;){var e=a.h[b];zd(a.k,e)&&(a.h[d++]=e);b++}a.h.length=d}if(a.j!=a.h.length){for(var f={},d=b=0;b<a.h.length;)e=a.h[b],zd(f,e)||(a.h[d++]=e,f[e]=1),b++;a.h.length=d}}o.get=function(a,b){return zd(this.k,a)?this.k[a]:b};o.set=function(a,b){zd(this.k,a)||(this.j++,this.h.push(a),this.yb++);this.k[a]=b};
o.$a=function(a){var b;if(a instanceof xd)yd(a),b=a.h.concat(),a=a.la();else{b=[];var d=0,e;for(e in a)b[d++]=e;a=Lb(a)}for(d=0;d<b.length;d++)this.set(b[d],a[d])};o.N=function(){return new xd(this)};function zd(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ad(a){this.k=new xd;a&&this.$a(a)}function Bd(a){var b=typeof a;return b=="object"&&a||b=="function"?"o"+ja(a):b.substr(0,1)+a}o=Ad.prototype;o.add=function(a){this.k.set(Bd(a),a)};o.$a=function(a){for(var a=wd(a),b=a.length,d=0;d<b;d++)this.add(a[d])};o.Wa=function(a){for(var a=wd(a),b=a.length,d=0;d<b;d++)this.remove(a[d])};o.remove=function(a){return this.k.remove(Bd(a))};o.clear=function(){this.k.clear()};o.contains=function(a){a=Bd(a);return zd(this.k.k,a)};
o.Yb=function(a){for(var b=new Ad,a=wd(a),d=0;d<a.length;d++){var e=a[d];this.contains(e)&&b.add(e)}return b};o.la=function(){return this.k.la()};o.N=function(){return new Ad(this)};function Cd(a,b,d){this.l=d||(a?A(Sb(a)):A());vd.call(this,this.l.ja("div",{style:"position:absolute;display:none;"}));this.hb=new x(1,1);this.$=new Ad;a&&(a=Sb(a),this.$.add(a),F(a,"mouseover",this.Sb,!1,this),F(a,"mouseout",this.Pa,!1,this),F(a,"mousemove",this.Rb,!1,this),F(a,"focus",this.Pb,!1,this),F(a,"blur",this.Pa,!1,this));b!=i&&fc(this.a(),b)}v(Cd,vd);var Dd=[];o=Cd.prototype;o.m=i;o.className="goog-tooltip";o.mc=500;o.Kc=0;o.lb=l("l");
o.detach=function(a){if(a)a=Sb(a),Ed(this,a),this.$.remove(a);else{for(var b=this.$.la(),d=0;a=b[d];d++)Ed(this,a);this.$.clear()}};function Ed(a,b){dd(b,"mouseover",a.Sb,!1,a);dd(b,"mouseout",a.Pa,!1,a);dd(b,"mousemove",a.Rb,!1,a);dd(b,"focus",a.Pb,!1,a);dd(b,"blur",a.Pa,!1,a)}o.vb=function(a){var b=this.a();b&&dc(b);Cd.i.vb.call(this,a);if(a)b=this.l.g.body,b.insertBefore(a,b.lastChild)};
o.qb=function(){if(!sd.prototype.qb.call(this))return!1;if(this.anchor)for(var a,b=0;a=Dd[b];b++)ec(a.a(),this.anchor)||td(a,!1);Za(Dd,this)>=0||Dd.push(this);a=this.a();a.className=this.className;Fd(this);F(a,"mouseover",this.Ub,!1,this);F(a,"mouseout",this.Tb,!1,this);Gd(this);return!0};
o.rb=function(){ab(Dd,this);for(var a=this.a(),b,d=0;b=Dd[d];d++)b.anchor&&ec(a,b.anchor)&&td(b,!1);this.ic&&Hd(this.ic);dd(a,"mouseover",this.Ub,!1,this);dd(a,"mouseout",this.Tb,!1,this);this.anchor=h;if((this.T?this.p?4:1:this.ma?3:this.p?2:0)==0)this.Xa=!1;sd.prototype.rb.call(this)};o.cc=function(a,b){if(this.anchor==a&&this.$.contains(this.anchor))if(this.Xa||!this.yd){if(td(this,!1),!this.p)this.anchor=a,this.sb=b||Id(this,0)||h,this.p&&this.G(),td(this,!0)}else this.anchor=h;this.T=h};
o.Rc=function(a){this.ma=h;a==this.anchor&&(this.m==i||this.m!=this.a()&&!this.$.contains(this.m))&&(!this.Bb||!this.Bb.m)&&td(this,!1)};function Jd(a,b){var d=gc(a.l);a.hb.x=b.clientX+d.x;a.hb.y=b.clientY+d.y}o.Sb=function(a){var b=Kd(this,a.target);this.m=b;Fd(this);if(b!=this.anchor){this.anchor=b;if(!this.T)this.T=rd(u(this.cc,this,b,h),this.mc);Ld(this);Jd(this,a)}};function Kd(a,b){try{for(;b&&!a.$.contains(b);)b=b.parentNode;return b}catch(d){return i}}o.Rb=function(a){Jd(this,a);this.Xa=!0};
o.Pb=function(a){this.m=a=Kd(this,a.target);this.Xa=!0;if(this.anchor!=a){this.anchor=a;var b=Id(this,1);Fd(this);if(!this.T)this.T=rd(u(this.cc,this,a,b),this.mc);Ld(this)}};function Id(a,b){if(b==0){var d=a.hb.N();return new Md(d)}return new Nd(a.m)}function Ld(a){if(a.anchor)for(var b,d=0;b=Dd[d];d++)if(ec(b.a(),a.anchor))b.Bb=a,a.ic=b}
o.Pa=function(a){var b=Kd(this,a.target),d=Kd(this,a.relatedTarget);if(b!=d){if(b==this.m)this.m=i;Gd(this);this.Xa=!1;this.p&&(!a.relatedTarget||!ec(this.a(),a.relatedTarget))?Hd(this):this.anchor=h}};o.Ub=function(){var a=this.a();if(this.m!=a)Fd(this),this.m=a};o.Tb=function(a){var b=this.a();if(this.m==b&&(!a.relatedTarget||!ec(b,a.relatedTarget)))this.m=i,Hd(this)};function Gd(a){if(a.T)qd.clearTimeout(a.T),a.T=h}
function Hd(a){if((a.T?a.p?4:1:a.ma?3:a.p?2:0)==2)a.ma=rd(u(a.Rc,a,a.anchor),a.Kc)}function Fd(a){if(a.ma)qd.clearTimeout(a.ma),a.ma=h}o.f=function(){td(this,!1);Gd(this);this.detach();this.a()&&dc(this.a());this.m=i;delete this.l;Cd.i.f.call(this)};function Md(a,b){od.call(this,a,b)}v(Md,od);Md.prototype.G=function(a,b,d){b=kc(a);b=nc(b);d=d?new Ua(d.top+10,d.right,d.bottom,d.left+10):new Ua(10,0,0,10);wc(this.gb,a,4,d,b,9)&496&&wc(this.gb,a,4,d,b,5)};function Nd(a){yc.call(this,a,3)}v(Nd,yc);
Nd.prototype.G=function(a,b,d){var e=new x(10,0);vc(this.element,this.Hb,a,b,e,d,9)&496&&vc(this.element,2,a,1,e,d,5)};function Pd(){this.kc=qa()}var Qd=new Pd;Pd.prototype.set=ba("kc");Pd.prototype.reset=function(){this.set(qa())};Pd.prototype.get=l("kc");function Rd(a){this.fd=a||"";this.pd=Qd}Rd.prototype.lc=!0;Rd.prototype.od=!0;Rd.prototype.nd=!0;Rd.prototype.nc=!1;function Sd(a){return a<10?"0"+a:String(a)}function Td(a,b){var d=(a.oc-b)/1E3,e=d.toFixed(3),f=0;if(d<1)f=2;else for(;d<100;)f++,d*=10;for(;f-- >0;)e=" "+e;return e}function Ud(a){Rd.call(this,a)}v(Ud,Rd);Ud.prototype.nc=!0;function Vd(a,b,d,e){(!ea(a)||!ea(b))&&c(Error("Start and end parameters must be arrays"));a.length!=b.length&&c(Error("Start and end points must be the same length"));this.Ha=a;this.Bc=b;this.duration=d;this.zb=e;this.coords=[]}v(Vd,pd);var Nb={},Wd=i;function Xd(){Yd();var a=qa(),b;for(b in Nb)Zd(Nb[b],a);Wd=Mb()?i:qd.setTimeout(Xd,20)}function Yd(){Wd&&(qd.clearTimeout(Wd),Wd=i)}function $d(a){a=ja(a);delete Nb[a];Mb()&&Yd()}o=Vd.prototype;o.H=0;o.Nb=0;o.r=0;o.startTime=i;o.Lb=i;o.nb=i;
o.play=function(a){if(a||this.H==0)this.r=0,this.coords=this.Ha;else if(this.H==1)return!1;$d(this);this.startTime=qa();this.H==-1&&(this.startTime-=this.duration*this.r);this.Lb=this.startTime+this.duration;this.nb=this.startTime;this.r||ae(this,"begin");ae(this,"play");this.H==-1&&ae(this,"resume");this.H=1;a=ja(this);a in Nb||(Nb[a]=this);Wd||(Wd=qd.setTimeout(Xd,20));Zd(this,this.startTime);return!0};o.stop=function(a){$d(this);this.H=0;if(a)this.r=1;be(this,this.r);ae(this,"stop");ae(this,"end")};
o.f=function(){this.H!=0&&this.stop(!1);ae(this,"destroy");Vd.i.f.call(this)};function Zd(a,b){a.r=(b-a.startTime)/(a.Lb-a.startTime);if(a.r>=1)a.r=1;a.Nb=1E3/(b-a.nb);a.nb=b;be(a,a.r);a.r==1?(a.H=0,$d(a),ae(a,"finish"),ae(a,"end")):a.H==1&&ae(a,"animate")}function be(a,b){ha(a.zb)&&(b=a.zb(b));a.coords=Array(a.Ha.length);for(var d=0;d<a.Ha.length;d++)a.coords[d]=(a.Bc[d]-a.Ha[d])*b+a.Ha[d]}function ae(a,b){a.dispatchEvent(new ce(b,a))}
function ce(a,b){C.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.zd=b.coords[2];this.duration=b.duration;this.r=b.r;this.td=b.Nb;this.state=b.H;this.rd=b}v(ce,C);function de(){}(function(a){a.Ob=function(){return a.Oc||(a.Oc=new a)}})(de);de.prototype.Uc=0;de.Ob();function ee(a){this.l=a||A();this.jd=fe}v(ee,pd);ee.prototype.Mc=de.Ob();var fe=i;o=ee.prototype;o.Wb=i;o.oa=!1;o.b=i;o.jd=i;o.Sc=i;o.F=i;o.V=i;o.ua=i;o.pc=!1;o.a=l("b");o.getParent=l("F");o.xb=function(a){this.F&&this.F!=a&&c(Error("Method not supported"));ee.i.xb.call(this,a)};o.lb=l("l");o.ja=function(){this.b=this.l.createElement("div")};o.ib=ba("b");o.Na=function(){this.oa=!0;ge(this,function(a){!a.oa&&a.a()&&a.Na()})};
o.ya=function(){ge(this,function(a){a.oa&&a.ya()});this.Oa&&this.Oa.Wa();this.oa=!1};o.f=function(){ee.i.f.call(this);this.oa&&this.ya();this.Oa&&(this.Oa.B(),delete this.Oa);ge(this,function(a){a.B()});!this.pc&&this.b&&dc(this.b);this.F=this.Sc=this.b=this.ua=this.V=i};o.Aa=l("b");function ge(a,b){a.V&&$a(a.V,b,h)}
o.removeChild=function(a,b){if(a){var d=t(a)?a:a.Wb||(a.Wb=":"+(a.Mc.Uc++).toString(36)),a=this.ua&&d?(d in this.ua?this.ua[d]:h)||i:i;if(d&&a){var e=this.ua;d in e&&delete e[d];ab(this.V,a);b&&(a.ya(),a.b&&dc(a.b));d=a;d==i&&c(Error("Unable to set parent component"));d.F=i;ee.i.xb.call(d,i)}}a||c(Error("Child is not in parent component"));return a};function he(a,b){ee.call(this,b);this.D=a||""}v(he,ee);o=he.prototype;o.ka=i;o.ea=!1;o.Ra=!1;o.ja=function(){this.b=this.lb().ja("input",{type:"text"});if(this.a().placeholder!=i)this.ea=!0};o.ib=function(a){he.i.ib.call(this,a);if(!this.D)this.D=a.getAttribute("label")||"";this.a().placeholder!=i?(this.ea=!0,this.a().placeholder=this.D):this.a().setAttribute("aria-label",this.D)};
o.Na=function(){he.i.Na.call(this);var a=new ld(this);G(a,this.a(),"focus",this.Qb);G(a,this.a(),"blur",this.Gc);this.ea?this.aa=a:(nb&&G(a,this.a(),["keypress",Fc,"keyup"],this.Hc),G(a,B(this.a())?B(this.a()).parentWindow||B(this.a()).defaultView:window,"load",this.Jc),this.aa=a,ie(this));je(this);this.a().Pc=this};o.ya=function(){he.i.ya.call(this);ke(this);this.a().Pc=i};function ie(a){if(!a.Cc&&a.aa&&a.a().form)G(a.aa,a.a().form,"submit",a.Ic),a.Cc=!0}function ke(a){if(a.aa)a.aa.B(),a.aa=i}
o.f=function(){he.i.f.call(this);ke(this)};o.Za="label-input-label";o.Qb=function(){this.Ra=!0;Ib(this.a(),this.Za);if(!this.ea&&!le(this)&&!this.Nc){var a=this,b=function(){a.a().value=""};y?rd(b,10):b()}};o.Gc=function(){if(!this.ea)nd(this.aa,this.a(),Ec,this.Qb),this.ka=i;this.Ra=!1;je(this)};o.Hc=function(a){if(a.keyCode==27){if(a.type==Fc)this.ka=this.a().value;else if(a.type=="keypress")this.a().value=this.ka;else if(a.type=="keyup")this.ka=i;a.preventDefault()}};
o.Ic=function(){if(!le(this))this.a().value="",rd(this.Fc,10,this)};o.Fc=function(){if(!le(this))this.a().value=this.D};o.Jc=function(){je(this)};function le(a){return a.a().value!=""&&a.a().value!=a.D}o.clear=function(){this.a().value="";if(this.ka!=i)this.ka=""};function je(a){if(a.ea){if(a.a().placeholder!=a.D)a.a().placeholder=a.D}else ie(a),a.a().setAttribute("aria-label",a.D);le(a)?Ib(a.a(),a.Za):(!a.Nc&&!a.Ra&&Hb(a.a(),a.Za),a.ea||rd(a.hd,10,a))}
o.hd=function(){if(this.a()&&!le(this)&&!this.Ra)this.a().value=this.D};function me(a){return ne(a||arguments.callee.caller,[])}
function ne(a,b){var d=[];if(Za(b,a)>=0)d.push("[...circular reference...]");else if(a&&b.length<50){d.push(oe(a)+"(");for(var e=a.arguments,f=0;f<e.length;f++){f>0&&d.push(", ");var g;g=e[f];switch(typeof g){case "object":g=g?"object":"null";break;case "string":break;case "number":g=String(g);break;case "boolean":g=g?"true":"false";break;case "function":g=(g=oe(g))?g:"[fn]";break;default:g=typeof g}g.length>40&&(g=g.substr(0,40)+"...");d.push(g)}b.push(a);d.push(")\n");try{d.push(ne(a.caller,b))}catch(j){d.push("[exception trying to get caller]\n")}}else a?
d.push("[...long stack...]"):d.push("[end]");return d.join("")}function oe(a){if(pe[a])return pe[a];a=String(a);if(!pe[a]){var b=/function ([^\(]+)/.exec(a);pe[a]=b?b[1]:"[Anonymous]"}return pe[a]}var pe={};function qe(a,b,d,e,f){this.reset(a,b,d,e,f)}qe.prototype.ld=0;qe.prototype.kb=i;qe.prototype.jb=i;var re=0;qe.prototype.reset=function(a,b,d,e,f){this.ld=typeof f=="number"?f:re++;this.oc=e||qa();this.pa=a;this.dc=b;this.Qc=d;delete this.kb;delete this.jb};qe.prototype.wb=ba("pa");function se(a){this.Tc=a}se.prototype.F=i;se.prototype.pa=i;se.prototype.V=i;se.prototype.Ba=i;function te(a,b){this.name=a;this.value=b}te.prototype.toString=l("name");var ue=new te("SHOUT",1200),ve=new te("SEVERE",1E3),we=new te("WARNING",900),xe=new te("INFO",800),ye=new te("CONFIG",700),ze=new te("FINE",500),Ae=new te("ALL",0);function Be(a){return Ce(a)}o=se.prototype;o.getParent=l("F");o.wb=ba("pa");
function De(a){if(a.pa)return a.pa;if(a.F)return De(a.F);Xa("Root logger has no level set.");return i}o.log=function(a,b,d){if(a.value>=De(this).value){a=this.Ec(a,b,d);b="log:"+a.dc;r.console&&(r.console.timeStamp?r.console.timeStamp(b):r.console.markTimeline&&r.console.markTimeline(b));r.msWriteProfilerMark&&r.msWriteProfilerMark(b);for(b=this;b;){var d=b,e=a;if(d.Ba)for(var f=0,g=h;g=d.Ba[f];f++)g(e);b=b.getParent()}}};
o.Ec=function(a,b,d){var e=new qe(a,String(b),this.Tc);if(d){e.kb=d;var f;var g=arguments.callee.caller;try{var j;var k=ca("window.location.href");if(t(d))j={message:d,name:"Unknown error",lineNumber:"Not available",fileName:k,stack:"Not available"};else{var n,p,q=!1;try{n=d.lineNumber||d.vd||"Not available"}catch(w){n="Not available",q=!0}try{p=d.fileName||d.filename||d.sourceURL||k}catch(D){p="Not available",q=!0}j=q||!d.lineNumber||!d.fileName||!d.stack?{message:d.message,name:d.name,lineNumber:n,
fileName:p,stack:d.stack||"Not available"}:d}f="Message: "+va(j.message)+'\nUrl: <a href="view-source:'+j.fileName+'" target="_new">'+j.fileName+"</a>\nLine: "+j.lineNumber+"\n\nBrowser stack:\n"+va(j.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+va(me(g)+"-> ")}catch(R){f="Exception trying to expose exception! You win, we lose. "+R}e.jb=f}return e};o.info=function(a,b){this.log(xe,a,b)};var Ee={},Fe=i;function Ge(){Fe||(Fe=new se(""),Ee[""]=Fe,Fe.wb(ye))}function He(){Ge();return Fe}
function Ce(a){Ge();var b;if(!(b=Ee[a])){b=new se(a);var d=a.lastIndexOf("."),e=a.substr(d+1),d=Ce(a.substr(0,d));if(!d.V)d.V={};d.V[e]=b;b.F=d;Ee[a]=b}return b};function Ie(a){this.gd=u(this.qc,this);this.Mb=new Ud;this.Zb=this.Mb.lc=!1;this.b=a;this.zc=this.b.ownerDocument||this.b.document;var a=A(this.b),b=i;if(y)b=a.g.createStyleSheet(),uc(b);else{var d=Tb(a.g,"head")[0];d||(b=Tb(a.g,"body")[0],d=a.ja("head"),b.parentNode.insertBefore(d,b));b=a.ja("style");uc(b);a.appendChild(d,b)}this.b.className+=" logdiv"}
Ie.prototype.qc=function(a){var b=this.b.scrollHeight-this.b.scrollTop-this.b.clientHeight<=100,d=this.zc.createElement("div");d.className="logmsg";var e=this.Mb,f;switch(a.pa.value){case ue.value:f="dbg-sh";break;case ve.value:f="dbg-sev";break;case we.value:f="dbg-w";break;case xe.value:f="dbg-i";break;default:f="dbg-f"}var g=[];g.push(e.fd," ");if(e.lc){var j=new Date(a.oc);g.push("[",Sd(j.getFullYear()-2E3)+Sd(j.getMonth()+1)+Sd(j.getDate())+" "+Sd(j.getHours())+":"+Sd(j.getMinutes())+":"+Sd(j.getSeconds())+
"."+Sd(Math.floor(j.getMilliseconds()/10)),"] ")}e.od&&g.push("[",Ba(Td(a,e.pd.get())),"s] ");e.nd&&g.push("[",va(a.Qc),"] ");g.push('<span class="',f,'">',ua(Ba(va(a.dc))));e.nc&&a.kb&&g.push("<br>",ua(Ba(a.jb||"")));g.push("</span><br>");d.innerHTML=g.join("");this.b.appendChild(d);if(b)this.b.scrollTop=this.b.scrollHeight};Ie.prototype.clear=function(){this.b.innerHTML=""};function Je(a,b){this.uc=a!==h?a:!0;this.mb=b||Ke;this.Ua=this.mb(this.Ea)}v(Je,pd);o=Je.prototype;o.u=i;o.U=i;o.ra=h;o.fb=!1;o.Ea=0;o.S=Ce("goog.net.WebSocket");var Le="closed_"+kd++,Me="error_"+kd++,Ne="message_"+kd++,Oe="opened_"+kd++;function Ke(a){return Math.min(Math.pow(2,a)*1E3,6E4)}o=Je.prototype;
o.open=function(a,b){Pe(this);this.U=a;(this.ra=b)?(this.S.info("Opening the WebSocket on "+this.U+" with protocol "+this.ra),this.u=new WebSocket(this.U,this.ra)):(this.S.info("Opening the WebSocket on "+this.U),this.u=new WebSocket(this.U));this.u.onopen=u(this.cd,this);this.u.onclose=u(this.Xc,this);this.u.onmessage=u(this.bd,this);this.u.onerror=u(this.Zc,this)};o.close=function(){Pe(this);if(this.u)this.S.info("Closing the WebSocket."),this.fb=!0,this.u.close(),this.u=i};o.send=function(a){this.u.send(a)};
o.cd=function(){this.S.info("WebSocket opened on "+this.U);this.dispatchEvent(Oe);this.Ea=0;this.Ua=this.mb(this.Ea)};
o.Xc=function(a){this.S.info("The WebSocket on "+this.U+" closed.");this.dispatchEvent(Le);this.u=i;if(this.fb)this.S.info("The WebSocket closed normally."),this.U=i,this.ra=h;else if(this.S.log(ve,"The WebSocket disconnected unexpectedly: "+a.data,h),this.uc)this.S.info("Seconds until next reconnect attempt: "+Math.floor(this.Ua/1E3)),this.ub=rd(u(this.open,this,this.U,this.ra),this.Ua,this),this.Ea++,this.Ua=this.mb(this.Ea);this.fb=!1};o.bd=function(a){this.dispatchEvent(new Qe(a.data))};
o.Zc=function(a){a=a.data;this.S.log(ve,"An error occurred: "+a,h);this.dispatchEvent(new Re(a))};function Pe(a){a.ub!=i&&qd.clearTimeout(a.ub);a.ub=i}o.f=function(){Je.i.f.call(this);this.close()};function Qe(a){C.call(this,Ne);this.message=a}v(Qe,C);function Re(a){C.call(this,Me);this.data=a}v(Re,C);function Se(a,b,d,e,f){function g(a){if(a)a.tabIndex=0,F(a,Ec,j.$c,!1,j),F(a,Fc,j.ad,!1,j)}this.l=f||A();this.P=this.l.a(a)||i;this.xa=this.l.a(e||i);this.La=(this.pb=ha(b)?b:i)||!b?i:this.l.a(b);this.R=d==!0;var j=this;g(this.P);g(this.xa);this.Ya(this.R)}v(Se,pd);o=Se.prototype;o.f=function(){this.P&&hd(this.P);this.xa&&hd(this.xa);Se.i.f.call(this)};o.Aa=l("La");
o.Ya=function(a){if(this.La)tc(this.La,a);else if(a&&this.pb)this.La=this.pb();this.xa?(tc(this.P,!a),tc(this.xa,a)):(Te(this,a),this.P&&this.P.setAttribute("aria-expanded",a));this.R=a;this.dispatchEvent(new Ue("toggle",this,this.R))};function Te(a,b){if(a.P){var d=a.P;b?Hb(d,"goog-zippy-expanded"):Ib(d,"goog-zippy-expanded");d=a.P;!b?Hb(d,"goog-zippy-collapsed"):Ib(d,"goog-zippy-collapsed")}}o.ad=function(a){if(a.keyCode==13||a.keyCode==32)this.Ya(!this.R),a.preventDefault(),a.stopPropagation()};
o.$c=function(){this.Ya(!this.R)};function Ue(a,b,d){C.call(this,a,b);this.sd=d}v(Ue,C);function Ve(a,b,d){var e=Xb("div",{style:"overflow:hidden"}),b=Sb(b);b.parentNode.replaceChild(e,b);e.appendChild(b);this.Ma=e;this.v=i;Se.call(this,a,b,d);a=this.R;this.Ma.style.display=a?"":"none";Te(this,a)}v(Ve,Se);o=Ve.prototype;o.sc=500;o.rc=function(a){return 1-Math.pow(1-a,3)};
o.Ya=function(a){if(this.R!=a||this.v){if(this.Ma.style.display=="none")this.Ma.style.display="";var b=this.Aa().offsetHeight,d=0;this.v?(a=this.R,hd(this.v),this.v.stop(!1),d=b-Math.abs(parseInt(this.Aa().style.marginTop,10))):d=a?0:b;Te(this,a);this.v=new Vd([0,d],[0,a?b:0],this.sc,this.rc);F(this.v,["begin","animate","end"],this.Vc,!1,this);F(this.v,"end",u(this.Wc,this,a));this.v.play(!1)}};o.Vc=function(a){var b=this.Aa();b.style.marginTop=a.y-b.offsetHeight+"px"};
o.Wc=function(a){if(a)this.Aa().style.marginTop="0";hd(this.v);this.R=a;this.v=i;if(!a)this.Ma.style.display="none";this.dispatchEvent(new Ue("toggle",this,a))};function H(a){return a!=i&&a!==!1}function We(a,b){var d=a[s.call(i,b)];return H(d)?d:(d=a._,H(d)?d:!1)}function Xe(a){return Array.prototype.slice.call(a)}function Ye(a){return Array.prototype.slice.call(arguments)}
var $e=function Ze(b){return H(H(b)?b.Y:b)?b.Y(b):function(){var d=Ze[s.call(i,b)];return H(d)?d:Ze._}().call(i,b)},bf=function af(b,d){return H(H(b)?b.I:b)?b.I(b,d):function(){var d=af[s.call(i,b)];return H(d)?d:af._}().call(i,b,d)},I=function(){function a(a,b,g){return H(H(a)?a.Ka:a)?a.Ka(a,b,g):function(){var b=d[s.call(i,a)];return H(b)?b:d._}().call(i,a,b,g)}function b(a,b){return H(H(a)?a.Ka:a)?a.Ka(a,b):function(){var b=d[s.call(i,a)];return H(b)?b:d._}().call(i,a,b)}var d=i;return d=function(d,
f,g){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,g)}c("Invalid arity: "+arguments.length)}}(),cf={},ef=function df(b){return H(H(b)?b.ga:b)?b.ga(b):function(){var d=df[s.call(i,b)];return H(d)?d:df._}().call(i,b)},gf=function ff(b){return H(H(b)?b.ha:b)?b.ha(b):function(){var d=ff[s.call(i,b)];return H(d)?d:ff._}().call(i,b)},J=function(){function a(a,b,g){return H(H(a)?a.Z:a)?a.Z(a,b,g):function(){var b=d[s.call(i,a)];return H(b)?b:d._}().call(i,a,b,g)}function b(a,
b){return H(H(a)?a.Z:a)?a.Z(a,b):function(){var b=d[s.call(i,a)];return H(b)?b:d._}().call(i,a,b)}var d=i;return d=function(d,f,g){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,g)}c("Invalid arity: "+arguments.length)}}(),jf=function hf(b,d){return H(H(b)?b.cb:b)?b.cb(b,d):function(){var d=hf[s.call(i,b)];return H(d)?d:hf._}().call(i,b,d)},lf=function kf(b,d,e){return H(H(b)?b.Ja:b)?b.Ja(b,d,e):function(){var d=kf[s.call(i,b)];return H(d)?d:kf._}().call(i,b,
d,e)},mf={},of=function nf(b,d){return H(H(b)?b.eb:b)?b.eb(b,d):function(){var d=nf[s.call(i,b)];return H(d)?d:nf._}().call(i,b,d)},pf={},rf=function qf(b,d){return H(H(b)?b.Db:b)?b.Db(0,d):function(){var d=qf[s.call(i,b)];return H(d)?d:qf._}().call(i,b,d)},sf={},uf=function tf(b){return H(H(b)?b.vc:b)?b.state:function(){var d=tf[s.call(i,b)];return H(d)?d:tf._}().call(i,b)},vf={},xf=function wf(b){return H(H(b)?b.L:b)?b.d:function(){var d=wf[s.call(i,b)];return H(d)?d:wf._}().call(i,b)},yf={},Af=
function zf(b,d){return H(H(b)?b.M:b)?b.M(b,d):function(){var d=zf[s.call(i,b)];return H(d)?d:zf._}().call(i,b,d)},Bf=function(){function a(a,b,g){return H(H(a)?a.va:a)?a.va(a,b,g):function(){var b=d[s.call(i,a)];return H(b)?b:d._}().call(i,a,b,g)}function b(a,b){return H(H(a)?a.va:a)?a.va(a,b):function(){var b=d[s.call(i,a)];return H(b)?b:d._}().call(i,a,b)}var d=i;return d=function(d,f,g){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,g)}c("Invalid arity: "+
arguments.length)}}(),Df=function Cf(b,d){return H(H(b)?b.o:b)?b.o(b,d):function(){var d=Cf[s.call(i,b)];return H(d)?d:Cf._}().call(i,b,d)},Ff=function Ef(b){return H(H(b)?b.J:b)?b.J(b):function(){var d=Ef[s.call(i,b)];return H(d)?d:Ef._}().call(i,b)},Hf=function Gf(b){return H(H(b)?b.A:b)?b.A(b):function(){var d=Gf[s.call(i,b)];return H(d)?d:Gf._}().call(i,b)},If={},Jf={},Lf=function Kf(b,d){return H(H(b)?b.s:b)?b.s(b,d):function(){var d=Kf[s.call(i,b)];return H(d)?d:Kf._}().call(i,b,d)};
function Mf(a,b){return a===b}function K(a,b){return Df.call(i,a,b)}function L(a){return Mf.call(i,a,i)}pf["null"]=!0;rf["null"]=m(i);Df["null"]=function(a,b){return L.call(i,b)};bf["null"]=function(a,b){return N.call(i,b)};cf["null"]=!0;ef["null"]=m(i);gf["null"]=function(){return N.call(i)};yf["null"]=!0;Af["null"]=m(i);mf["null"]=!0;of["null"]=m(i);I["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return i;case 3:return d}c("Invalid arity: "+arguments.length)}}();
vf["null"]=!0;xf["null"]=m(i);Bf["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return b.call(i);case 3:return d}c("Invalid arity: "+arguments.length)}}();Ff["null"]=m(0);$e["null"]=m(0);lf["null"]=function(a,b,d){return Nf.call(i,b,d)};J["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return i;case 3:return d}c("Invalid arity: "+arguments.length)}}();r.Date.prototype.o=function(a,b){return Mf.call(i,a.toString,b.toString)};Ff.number=aa();
Df.number=function(a,b){return Mf.call(i,a,b)};Ff["function"]=function(a){return ja.call(i,a)};function O(a){return a+1}function Of(a,b){return a<b}
var Pf=function(){return function(a,b,d,e){switch(arguments.length){case 2:var f;a:if(H(K.call(i,0,$e.call(i,a))))f=b.call(i);else for(var g=I.call(i,a,0),j=1;;)if(H(Of.call(i,j,$e.call(i,a))))g=b.call(i,g,I.call(i,a,j)),j=O.call(i,j);else{f=g;break a}return f;case 3:a:{f=d;for(j=0;;)if(H(Of.call(i,j,$e.call(i,a))))f=b.call(i,f,I.call(i,a,j)),j=O.call(i,j);else{g=f;break a}}return g;case 4:a:{f=d;for(g=e;;)if(H(Of.call(i,g,$e.call(i,a))))f=b.call(i,f,I.call(i,a,g)),g=O.call(i,g);else{j=f;break a}}return j}c("Invalid arity: "+
arguments.length)}}();function Qf(a,b){this.fa=a;this.na=b}o=Qf.prototype;o.va=function(){return function(a,b,d){switch(arguments.length){case 2:return Pf.call(i,this.fa,b,this.fa[this.na],O.call(i,this.na));case 3:return Pf.call(i,this.fa,b,d,this.na)}c("Invalid arity: "+arguments.length)}}();o.o=function(a,b){return Rf.call(i,a,b)};o.ia=!0;o.wa=!0;o.ga=function(){return this.fa[this.na]};
o.ha=function(){return H(Of.call(i,O.call(i,this.na),$e.call(i,this.fa)))?new Qf(this.fa,O.call(i,this.na)):N.call(i)};o.A=aa();function Sf(a,b){return H(K.call(i,0,$e.call(i,a)))?i:new Qf(a,b)}function P(a,b){return Sf.call(i,a,b)}Bf.array=function(){return function(a,b,d){switch(arguments.length){case 2:return Pf.call(i,a,b);case 3:return Pf.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
J.array=function(){return function(a,b,d){switch(arguments.length){case 2:return a[b];case 3:return I.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();I.array=function(){return function(a,b,d){switch(arguments.length){case 2:return H(Of.call(i,b,a.length))?a[b]:i;case 3:return H(Of.call(i,b,a.length))?a[b]:d}c("Invalid arity: "+arguments.length)}}();$e.array=function(a){return a.length};Hf.array=function(a){return P.call(i,a,0)};function Q(a){return H(a)?Hf.call(i,a):i}
function S(a){a=Q.call(i,a);return H(a)?ef.call(i,a):i}function T(a){return gf.call(i,Q.call(i,a))}function U(a){return H(a)?Q.call(i,T.call(i,a)):i}function Tf(a){return S.call(i,U.call(i,a))}function Uf(a){return U.call(i,U.call(i,a))}$e._=function(a){for(var a=Q.call(i,a),b=0;;)if(H(a))a=U.call(i,a),b=O.call(i,b);else return b};Df._=function(a,b){return Mf.call(i,a,b)};function Vf(a){return H(a)?!1:!0}
var V=function(){function a(a,e,f){for(var g=P(Array.prototype.slice.call(arguments,2),0);;)if(H(g))var j=b.call(i,a,e),k=S.call(i,g),g=U.call(i,g),a=j,e=k;else return b.call(i,a,e)}var b=i,b=function(b,e,f){switch(arguments.length){case 2:return bf.call(i,b,e);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}();function Wf(a){return $e.call(i,a)}
var W=function(){return function(a,b,d){switch(arguments.length){case 2:return I.call(i,a,b);case 3:return I.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}(),Xf=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,a,b);case 3:return J.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}(),Yf=function(){function a(a,e,f,g){for(var j=P(Array.prototype.slice.call(arguments,3),0);;){var k=b.call(i,a,e,f);if(H(j))var n=S.call(i,j),p=Tf.call(i,j),j=Uf.call(i,j),a=k,
e=n,f=p;else return k}}var b=i,b=function(b,e,f,g){switch(arguments.length){case 3:return lf.call(i,b,e,f);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=3;b.c=function(b){var e=S(b),f=S(U(b)),g=S(U(U(b))),b=T(U(U(b)));return a.call(i,e,f,g,b)};return b}(),Zf=function(){function a(a,e,f){for(var g=P(Array.prototype.slice.call(arguments,2),0);;){var j=b.call(i,a,e);if(H(g))var k=S.call(i,g),g=U.call(i,g),a=j,e=k;else return j}}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return b;
case 2:return of.call(i,b,e);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}();function $f(a,b){return Af.call(i,a,b)}function ag(a){return xf.call(i,a)}
var bg=function(){function a(a,e,f){for(var g=P(Array.prototype.slice.call(arguments,2),0);;){var j=b.call(i,a,e);if(H(g))var k=S.call(i,g),g=U.call(i,g),a=j,e=k;else return j}}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return b;case 2:return rf.call(i,b,e);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}();function cg(a){return Ff.call(i,a)}
function dg(a){return Vf.call(i,Q.call(i,a))}function eg(a){return H(L.call(i,a))?!1:H(H(a)?a.wc:a)?!0:We.call(i,pf,a)}function fg(a){return H(H(a)?a.ia:a)?!0:We.call(i,If,a)}function gg(a){return H(L.call(i,a))?!1:H(H(a)?a.Cb:a)?!0:We.call(i,mf,a)}function hg(a){return H(H(a)?a.xc:a)?!0:We.call(i,sf,a)}function ig(){return{}}function jg(a){var b=Ye.call(i);Kb.call(i,a,function(a,e){return b.push(e)});return b}function kg(a,b){return delete a[b]}var lg=ig.call(i);function mg(a){return h===a}
function ng(a,b){return b instanceof a}function og(a){return H(L.call(i,a))?!1:H(H(a)?a.wa:a)?!0:We.call(i,cf,a)}function pg(a){return H(a)?!0:!1}function qg(a){var b=t.call(i,a);return H(b)?Vf.call(i,function(){var b=K.call(i,a.charAt(0),"\ufdd0");return H(b)?b:K.call(i,a.charAt(0),"\ufdd1")}()):b}function rg(a){var b=t.call(i,a);return H(b)?K.call(i,a.charAt(0),"\ufdd0"):b}function sg(a){var b=t.call(i,a);return H(b)?K.call(i,a.charAt(0),"\ufdd1"):b}function tg(a){return ga.call(i,a)}
function ug(a){var b=tg.call(i,a);return H(b)?a==a.toFixed():b}function vg(a,b){return H(Mf.call(i,J.call(i,a,b,lg),lg))?!1:!0}function wg(a,b){return gb.call(i,a,b)}function xg(a){return H(K.call(i,a,wg))?wg:function(b,d){var e=a.call(i,b,d);return H(tg.call(i,e))?e:H(e)?-1:H(a.call(i,d,b))?1:0}}
var Ag=function(){var a=i;return a=function(b,d){switch(arguments.length){case 1:return a.call(i,wg,b);case 2:var e;H(Q.call(i,d))?(e=yg.call(i,d),hb.call(i,e,xg.call(i,b)),e=Q.call(i,e)):e=zg;return e}c("Invalid arity: "+arguments.length)}}(),Bg=function(){return function(a,b,d){switch(arguments.length){case 2:return Bf.call(i,b,a);case 3:return Bf.call(i,d,a,b)}c("Invalid arity: "+arguments.length)}}(),Cg=function(){return function(a,b,d){switch(arguments.length){case 2:var e=Q.call(i,b);return H(e)?
Bg.call(i,a,S.call(i,e),U.call(i,e)):a.call(i);case 3:a:for(var f=b,g=Q.call(i,d);;)if(H(g))f=a.call(i,f,S.call(i,g)),g=U.call(i,g);else{e=f;break a}return e}c("Invalid arity: "+arguments.length)}}();Bf._=function(){return function(a,b,d){switch(arguments.length){case 2:return Cg.call(i,b,a);case 3:return Cg.call(i,b,d,a)}c("Invalid arity: "+arguments.length)}}();
var Dg=function(){function a(a,e,f){var g=P(Array.prototype.slice.call(arguments,2),0);return Bg.call(i,b,b.call(i,a,e),g)}var b=i,b=function(b,e,f){switch(arguments.length){case 0:return 0;case 1:return b;case 2:return b+e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}(),Eg=function(){function a(a,e,f){var g=P(Array.prototype.slice.call(arguments,2),0);return Bg.call(i,b,b.call(i,
a,e),g)}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return-b;case 2:return b-e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}(),Fg=function(){function a(a,e,f){var g=P(Array.prototype.slice.call(arguments,2),0);return Bg.call(i,b,b.call(i,a,e),g)}var b=i,b=function(b,e,f){switch(arguments.length){case 0:return 1;case 1:return b;case 2:return b*e;default:return a.apply(this,
arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}(),Gg=function(){function a(a,e,f){var g=P(Array.prototype.slice.call(arguments,2),0);return Bg.call(i,b,b.call(i,a,e),g)}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return 1/b;case 2:return b/e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}(),
Hg=function(){function a(a,e,f){for(var g=P(Array.prototype.slice.call(arguments,2),0);;)if(H(b.call(i,a,e)))if(H(U.call(i,g)))var j=e,k=S.call(i,g),g=U.call(i,g),a=j,e=k;else return b.call(i,e,S.call(i,g));else return!1}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return b<e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}(),Ig=function(){function a(a,e,
f){for(var g=P(Array.prototype.slice.call(arguments,2),0);;)if(H(b.call(i,a,e)))if(H(U.call(i,g)))var j=e,k=S.call(i,g),g=U.call(i,g),a=j,e=k;else return b.call(i,e,S.call(i,g));else return!1}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return b<=e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}(),Jg=function(){function a(a,e,f){for(var g=P(Array.prototype.slice.call(arguments,
2),0);;)if(H(b.call(i,a,e)))if(H(U.call(i,g)))var j=e,k=S.call(i,g),g=U.call(i,g),a=j,e=k;else return b.call(i,e,S.call(i,g));else return!1}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return b>e;default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}();function Kg(a){return Eg.call(i,a,1)}function Lg(a,b){return a^b}function Mg(a,b){return a&b}
function Ng(a,b){return a<<b}function Og(a,b){return a>>b}
var Pg=function(){function a(a,e,f){for(var g=P(Array.prototype.slice.call(arguments,2),0);;)if(H(b.call(i,a,e)))if(H(U.call(i,g)))var j=e,k=S.call(i,g),g=U.call(i,g),a=j,e=k;else return b.call(i,e,S.call(i,g));else return!1}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return Df.call(i,b,e);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}();
function Qg(a){return Hg.call(i,0,a)}function Rg(a){return Pg.call(i,0,a)}function Sg(a,b){for(var d=b,e=Q.call(i,a);;)if(H(function(){var a=e;return H(a)?Qg.call(i,d):a}()))var f=Kg.call(i,d),g=U.call(i,e),d=f,e=g;else return e}I._=function(){return function(a,b,d){switch(arguments.length){case 2:var e;var f=Sg.call(i,a,b);H(f)?e=S.call(i,f):c("Index out of bounds");return e;case 3:return e=Sg.call(i,a,b),H(e)?S.call(i,e):d}c("Invalid arity: "+arguments.length)}}();
var X=function(){function a(a,e){var f=P(Array.prototype.slice.call(arguments,1),0);return function(a,d){for(;;)if(H(d))var e=a.append(b.call(i,S.call(i,d))),f=U.call(i,d),a=e,d=f;else return b.call(i,a)}.call(i,new Sa(b.call(i,a)),f)}var b=i,b=function(b,e){switch(arguments.length){case 0:return"";case 1:return H(L.call(i,b))?"":b.toString();default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=1;b.c=function(b){var e=S(b),b=T(b);return a.call(i,e,b)};return b}(),Tg=function(){return function(a,
b,d){switch(arguments.length){case 2:return a.substring(b);case 3:return a.substring(b,d)}c("Invalid arity: "+arguments.length)}}(),Ug=function(){var a=i;return a=function(b,d){switch(arguments.length){case 1:return H(sg.call(i,b))?b:H(rg.call(i,b))?X.call(i,"\ufdd1","'",Tg.call(i,b,2)):H("\ufdd0'else")?X.call(i,"\ufdd1","'",b):i;case 2:return a.call(i,X.call(i,b,"/",d))}c("Invalid arity: "+arguments.length)}}(),Vg=function(){var a=i;return a=function(b,d){switch(arguments.length){case 1:return H(rg.call(i,
b))?b:H(sg.call(i,b))?X.call(i,"\ufdd0","'",Tg.call(i,b,2)):H("\ufdd0'else")?X.call(i,"\ufdd0","'",b):i;case 2:return a.call(i,X.call(i,b,"/",d))}c("Invalid arity: "+arguments.length)}}();function Rf(a,b){return pg.call(i,H(fg.call(i,b))?function(){for(var d=Q.call(i,a),e=Q.call(i,b);;)if(H(L.call(i,d)))return L.call(i,e);else if(H(L.call(i,e)))return!1;else if(H(K.call(i,S.call(i,d),S.call(i,e))))d=U.call(i,d),e=U.call(i,e);else return H("\ufdd0'else")?!1:i}():i)}
function Wg(a,b){return Lg.call(i,a,Dg.call(i,b,2654435769,Ng.call(i,a,6),Og.call(i,a,2)))}function Xg(a){return Bg.call(i,function(a,d){return Wg.call(i,a,cg.call(i,d))},cg.call(i,S.call(i,a)),U.call(i,a))}function Yg(a,b,d,e){this.d=a;this.za=b;this.sa=d;this.count=e}o=Yg.prototype;o.o=function(a,b){return Rf.call(i,a,b)};o.I=function(a,b){return new Yg(this.d,b,a,O.call(i,this.count))};o.wa=!0;o.ga=l("za");o.ha=l("sa");o.A=aa();o.W=!0;o.M=function(a,b){return new Yg(b,this.za,this.sa,this.count)};
o.K=!0;o.L=l("d");o.J=function(a){return Xg.call(i,a)};o.Y=l("count");o.ia=!0;function Zg(a){this.d=a}o=Zg.prototype;o.o=function(a,b){return Rf.call(i,a,b)};o.I=function(a,b){return new Yg(this.d,b,i,1)};o.wa=!0;o.ga=m(i);o.ha=m(i);o.A=m(i);o.W=!0;o.M=function(a,b){return new Zg(b)};o.K=!0;o.L=l("d");o.J=function(a){return Xg.call(i,a)};o.Y=m(0);o.ia=!0;var zg=new Zg(i);function $g(a){return Bg.call(i,V,zg,a)}
function N(a){var b=P(Array.prototype.slice.call(arguments,0),0);return Bg.call(i,V,zg,$g.call(i,b))}function ah(a,b,d){this.d=a;this.za=b;this.sa=d}o=ah.prototype;o.A=aa();o.J=function(a){return Xg.call(i,a)};o.o=function(a,b){return Rf.call(i,a,b)};o.ia=!0;o.I=function(a,b){return new ah(i,b,a)};o.wa=!0;o.ga=l("za");o.ha=function(){return H(L.call(i,this.sa))?zg:this.sa};o.K=!0;o.L=l("d");o.W=!0;o.M=function(a,b){return new ah(b,this.za,this.sa)};function Y(a,b){return new ah(i,a,b)}
Bf.string=function(){return function(a,b,d){switch(arguments.length){case 2:return Pf.call(i,a,b);case 3:return Pf.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();J.string=function(){return function(a,b,d){switch(arguments.length){case 2:return I.call(i,a,b);case 3:return I.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
I.string=function(){return function(a,b,d){switch(arguments.length){case 2:return H(Hg.call(i,b,$e.call(i,a)))?a.charAt(b):i;case 3:return H(Hg.call(i,b,$e.call(i,a)))?a.charAt(b):d}c("Invalid arity: "+arguments.length)}}();$e.string=function(a){return a.length};Hf.string=function(a){return Sf.call(i,a,0)};Ff.string=function(a){return Ja.call(i,a)};
r.String.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return Xf.call(i,b,this.toString());case 3:return Xf.call(i,b,this.toString(),d)}c("Invalid arity: "+arguments.length)}}();function bh(a){var b=a.x;return H(a.tb)?b:(a.x=b.call(i),a.tb=!0,a.x)}function Z(a,b,d){this.d=a;this.tb=b;this.x=d}o=Z.prototype;o.A=function(a){return Q.call(i,bh.call(i,a))};o.J=function(a){return Xg.call(i,a)};o.o=function(a,b){return Rf.call(i,a,b)};o.ia=!0;
o.I=function(a,b){return Y.call(i,b,a)};o.wa=!0;o.ga=function(a){return S.call(i,bh.call(i,a))};o.ha=function(a){return T.call(i,bh.call(i,a))};o.K=!0;o.L=l("d");o.W=!0;o.M=function(a,b){return new Z(b,this.tb,this.x)};function yg(a){for(var b=Ye.call(i);;)if(H(Q.call(i,a)))b.push(S.call(i,a)),a=U.call(i,a);else return b}function ch(a,b){for(var d=a,e=b,f=0;;)if(H(function(){var a=Qg.call(i,e);return H(a)?Q.call(i,d):a}()))var g=U.call(i,d),j=Kg.call(i,e),f=O.call(i,f),d=g,e=j;else return f}
var eh=function dh(b){return H(L.call(i,b))?i:H(L.call(i,U.call(i,b)))?Q.call(i,S.call(i,b)):H("\ufdd0'else")?Y.call(i,S.call(i,b),dh.call(i,U.call(i,b))):i},fh=function(){function a(a,b,d){var e=P(Array.prototype.slice.call(arguments,2),0);return function q(a,b){return new Z(i,!1,function(){var d=Q.call(i,a);return H(d)?Y.call(i,S.call(i,d),q.call(i,T.call(i,d),b)):H(b)?q.call(i,S.call(i,b),U.call(i,b)):i})}.call(i,f.call(i,a,b),e)}function b(a,b){return new Z(i,!1,function(){var d=Q.call(i,a);return H(d)?
Y.call(i,S.call(i,d),f.call(i,T.call(i,d),b)):b})}function d(a){return new Z(i,!1,function(){return a})}function e(){return new Z(i,!1,m(i))}var f=i,f=function(g,f,k){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,g);case 2:return b.call(this,g,f);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};f.e=2;f.c=function(b){var d=S(b),e=S(U(b)),b=T(U(b));return a.call(i,d,e,b)};return f}(),gh=function(){function a(a,b,f,g,j){var k=P(Array.prototype.slice.call(arguments,
4),0);return Y.call(i,a,Y.call(i,b,Y.call(i,f,Y.call(i,g,eh.call(i,k)))))}var b=i,b=function(b,e,f,g,j){switch(arguments.length){case 1:return Q.call(i,b);case 2:return Y.call(i,b,e);case 3:return Y.call(i,b,Y.call(i,e,f));case 4:return Y.call(i,b,Y.call(i,e,Y.call(i,f,g)));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=4;b.c=function(b){var e=S(b),f=S(U(b)),g=S(U(U(b))),j=S(U(U(U(b)))),b=T(U(U(U(b))));return a.call(i,e,f,g,j,b)};return b}(),hh=function(){function a(a,
b,f,g,j,k){var n=P(Array.prototype.slice.call(arguments,5),0),n=Y.call(i,b,Y.call(i,f,Y.call(i,g,Y.call(i,j,eh.call(i,n))))),p=a.e;return H(a.c)?H(Ig.call(i,ch.call(i,n,p),p))?a.apply(a,yg.call(i,n)):a.c(n):a.apply(a,yg.call(i,n))}var b=i,b=function(b,e,f,g,j,k){switch(arguments.length){case 2:var n=b,p=e,q=n.e;return H(n.c)?H(Ig.call(i,ch.call(i,p,q),q))?n.apply(n,yg.call(i,p)):n.c(p):n.apply(n,yg.call(i,p));case 3:return n=b,p=gh.call(i,e,f),q=n.e,H(n.c)?H(Ig.call(i,ch.call(i,p,q),q))?n.apply(n,
yg.call(i,p)):n.c(p):n.apply(n,yg.call(i,p));case 4:return n=b,p=gh.call(i,e,f,g),q=n.e,H(n.c)?H(Ig.call(i,ch.call(i,p,q),q))?n.apply(n,yg.call(i,p)):n.c(p):n.apply(n,yg.call(i,p));case 5:return n=b,p=gh.call(i,e,f,g,j),q=n.e,H(n.c)?H(Ig.call(i,ch.call(i,p,q),q))?n.apply(n,yg.call(i,p)):n.c(p):n.apply(n,yg.call(i,p));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=5;b.c=function(b){var e=S(b),f=S(U(b)),g=S(U(U(b))),j=S(U(U(U(b)))),k=S(U(U(U(U(b))))),b=T(U(U(U(U(b)))));
return a.call(i,e,f,g,j,k,b)};return b}(),ih=function(){function a(a,b,f){var g=P(Array.prototype.slice.call(arguments,2),0);return Vf.call(i,hh.call(i,K,a,b,g))}var b=i,b=function(b,e,f){switch(arguments.length){case 1:return!1;case 2:return Vf.call(i,K.call(i,b,e));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}();
function jh(a,b){for(;;)if(H(L.call(i,Q.call(i,b))))return!0;else if(H(a.call(i,S.call(i,b))))var d=a,e=U.call(i,b),a=d,b=e;else return H("\ufdd0'else")?!1:i}function kh(a,b){for(;;)if(H(Q.call(i,b))){var d=a.call(i,S.call(i,b));if(H(d))return d;else var d=a,e=U.call(i,b),a=d,b=e}else return i}function lh(a){if(H(ug.call(i,a)))return Rg.call(i,Mg.call(i,a,1));else c(X.call(i,"Argument must be an integer: ",a))}function mh(a){return Vf.call(i,lh.call(i,a))}function nh(a){return a}
var oh=function(){function a(a,b,d,e,p){var q=P(Array.prototype.slice.call(arguments,4),0);return f.call(i,function(b){return hh.call(i,a,b)},function D(a){return new Z(i,!1,function(){var b=f.call(i,Q,a);return H(jh.call(i,nh,b))?Y.call(i,f.call(i,S,b),D.call(i,f.call(i,T,b))):i})}.call(i,V.call(i,q,e,d,b)))}function b(a,b,d,e){return new Z(i,!1,function(){var p=Q.call(i,b),q=Q.call(i,d),w=Q.call(i,e);return H(H(p)?H(q)?w:q:p)?Y.call(i,a.call(i,S.call(i,p),S.call(i,q),S.call(i,w)),f.call(i,a,T.call(i,
p),T.call(i,q),T.call(i,w))):i})}function d(a,b,d){return new Z(i,!1,function(){var e=Q.call(i,b),p=Q.call(i,d);return H(H(e)?p:e)?Y.call(i,a.call(i,S.call(i,e),S.call(i,p)),f.call(i,a,T.call(i,e),T.call(i,p))):i})}function e(a,b){return new Z(i,!1,function(){var d=Q.call(i,b);return H(d)?Y.call(i,a.call(i,S.call(i,d)),f.call(i,a,T.call(i,d))):i})}var f=i,f=function(f,j,k,n,p){switch(arguments.length){case 2:return e.call(this,f,j);case 3:return d.call(this,f,j,k);case 4:return b.call(this,f,j,k,
n);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};f.e=4;f.c=function(b){var d=S(b),e=S(U(b)),f=S(U(U(b))),p=S(U(U(U(b)))),b=T(U(U(U(b))));return a.call(i,d,e,f,p,b)};return f}(),qh=function ph(b,d){return new Z(i,!1,function(){if(H(Qg.call(i,b))){var e=Q.call(i,d);return H(e)?Y.call(i,S.call(i,e),ph.call(i,Kg.call(i,b),T.call(i,e))):i}else return i})};
function rh(a,b){function d(a,b){for(;;){var d=Q.call(i,b);if(H(function(){var b=Qg.call(i,a);return H(b)?d:b}()))var j=Kg.call(i,a),k=T.call(i,d),a=j,b=k;else return d}}return new Z(i,!1,function(){return d.call(i,a,b)})}
var sh=function(){function a(a){return new Z(i,!1,function(){return Y.call(i,a,b.call(i,a))})}var b=i;return b=function(d,e){switch(arguments.length){case 1:return a.call(this,d);case 2:return qh.call(i,d,b.call(i,e))}c("Invalid arity: "+arguments.length)}}(),th=function(){function a(a,b,g){var j=P(Array.prototype.slice.call(arguments,2),0);return new Z(i,!1,function(){var g=oh.call(i,Q,V.call(i,j,b,a));return H(jh.call(i,nh,g))?fh.call(i,oh.call(i,S,g),hh.call(i,d,oh.call(i,T,g))):i})}function b(a,
b){return new Z(i,!1,function(){var g=Q.call(i,a),j=Q.call(i,b);return H(H(g)?j:g)?Y.call(i,S.call(i,g),Y.call(i,S.call(i,j),d.call(i,T.call(i,g),T.call(i,j)))):i})}var d=i,d=function(d,f,g){switch(arguments.length){case 2:return b.call(this,d,f);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};d.e=2;d.c=function(b){var d=S(b),g=S(U(b)),b=T(U(b));return a.call(i,d,g,b)};return d}();function uh(a,b){return rh.call(i,1,th.call(i,sh.call(i,a),b))}
function vh(a){return function d(a,f){return new Z(i,!1,function(){var g=Q.call(i,a);return H(g)?Y.call(i,S.call(i,g),d.call(i,T.call(i,g),f)):H(Q.call(i,f))?d.call(i,S.call(i,f),T.call(i,f)):i})}.call(i,i,a)}
var wh=function(){function a(a,b,f){var g=P(Array.prototype.slice.call(arguments,2),0);return vh.call(i,hh.call(i,oh,a,b,g))}var b=i,b=function(b,e,f){switch(arguments.length){case 2:return vh.call(i,oh.call(i,b,e));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=2;b.c=function(b){var e=S(b),f=S(U(b)),b=T(U(b));return a.call(i,e,f,b)};return b}();function xh(a,b){return Bg.call(i,bf,a,b)}
var yh=function(){function a(a,b,g,j){return new Z(i,!1,function(){var k=Q.call(i,j);if(H(k)){var n=qh.call(i,a,k);return H(K.call(i,a,Wf.call(i,n)))?Y.call(i,n,d.call(i,a,b,g,rh.call(i,b,k))):N.call(i,qh.call(i,a,fh.call(i,n,g)))}else return i})}function b(a,b,g){return new Z(i,!1,function(){var j=Q.call(i,g);if(H(j)){var k=qh.call(i,a,j);return H(K.call(i,a,Wf.call(i,k)))?Y.call(i,k,d.call(i,a,b,rh.call(i,b,j))):i}else return i})}var d=i;return d=function(e,f,g,j){switch(arguments.length){case 2:return d.call(i,
e,e,f);case 3:return b.call(this,e,f,g);case 4:return a.call(this,e,f,g,j)}c("Invalid arity: "+arguments.length)}}();function zh(a,b){this.d=a;this.n=b}o=zh.prototype;o.o=function(a,b){return Rf.call(i,a,b)};o.I=function(a,b){var d=Xe.call(i,this.n);d.push(b);return new zh(this.d,d)};o.A=function(){var a=this;return H(Jg.call(i,a.n.length,0))?function d(e){return new Z(i,!1,function(){return H(Hg.call(i,e,a.n.length))?Y.call(i,a.n[e],d.call(i,O.call(i,e))):i})}.call(i,0):i};o.xc=!0;o.W=!0;
o.M=function(a,b){return new zh(b,this.n)};o.Ka=function(){function a(a,b,f){var g=this;return H(function(){var a=Ig.call(i,0,b);return H(a)?Hg.call(i,b,g.n.length):a}())?g.n[b]:f}function b(a,b){var f=this;return H(function(){var a=Ig.call(i,0,b);return H(a)?Hg.call(i,b,f.n.length):a}())?f.n[b]:i}return function(d,e,f){switch(arguments.length){case 2:return b.call(this,0,e);case 3:return a.call(this,0,e,f)}c("Invalid arity: "+arguments.length)}}();o.K=!0;o.L=l("d");
o.va=function(){return function(a,b,d){switch(arguments.length){case 2:return Pf.call(i,this.n,b);case 3:return Pf.call(i,this.n,b,d)}c("Invalid arity: "+arguments.length)}}();o.J=function(a){return Xg.call(i,a)};o.Y=function(){return this.n.length};o.ia=!0;o.Ja=function(a,b,d){a=Xe.call(i,this.n);a[b]=d;return new zh(this.d,a)};o.Z=function(){return function(a,b,d){switch(arguments.length){case 2:return I.call(i,a,b,i);case 3:return I.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
var Ah=new zh(i,Ye.call(i));function Bh(a){return new zh(i,a)}zh.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,this,b);case 3:return J.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Ch(a){return Bg.call(i,V,Ah,a)}function Dh(a){var b=P(Array.prototype.slice.call(arguments,0),0);return Ch.call(i,b)}function Eh(){}Eh.prototype.o=m(!1);var Fh=new Eh;
function Gh(a,b){return pg.call(i,H(gg.call(i,b))?H(K.call(i,Wf.call(i,a),Wf.call(i,b)))?jh.call(i,nh,oh.call(i,function(a){return K.call(i,Xf.call(i,b,S.call(i,a),Fh),Tf.call(i,a))},a)):i:i)}function Hh(a,b,d){for(var e=d.length,f=0;;)if(H(Hg.call(i,f,e)))if(H(K.call(i,b,d[f])))return f;else f=Dg.call(i,f,a);else return i}
var Ih=function(){function a(a,b,f,g){return H(function(){var f=t.call(i,a);return H(f)?b.hasOwnProperty(a):f}())?f:g}var b=i;return b=function(d,e,f,g){switch(arguments.length){case 2:return b.call(i,d,e,!0,!1);case 4:return a.call(this,d,e,f,g)}c("Invalid arity: "+arguments.length)}}();function Jh(a,b,d){this.d=a;this.keys=b;this.X=d}o=Jh.prototype;o.o=function(a,b){return Gh.call(i,a,b)};o.I=function(a,b){return H(hg.call(i,b))?lf.call(i,a,I.call(i,b,0),I.call(i,b,1)):Bg.call(i,bf,a,b)};
o.A=function(){var a=this;return H(Qg.call(i,a.keys.length))?oh.call(i,function(b){return Dh.call(i,b,a.X[b])},a.keys):i};o.W=!0;o.M=function(a,b){return new Jh(b,this.keys,this.X)};o.Cb=!0;o.eb=function(a,b){var d=this;if(H(function(){var a=t.call(i,b);return H(a)?d.X.hasOwnProperty(b):a}())){var e=Xe.call(i,d.keys),f=Ob.call(i,d.X);e.splice(Hh.call(i,1,b,e),1);kg.call(i,f,b);return new Jh(d.d,e,f)}else return a};o.K=!0;o.L=l("d");o.J=function(a){return Xg.call(i,a)};o.Y=function(){return this.keys.length};
o.Ja=function(a,b,d){if(H(t.call(i,b))){var a=Ob.call(i,this.X),e=a.hasOwnProperty(b);a[b]=d;return H(e)?new Jh(this.d,this.keys,a):(d=Xe.call(i,this.keys),d.push(b),new Jh(this.d,d,a))}else return $f.call(i,xh.call(i,Nf.call(i,b,d),Q.call(i,a)),this.d)};o.cb=function(a,b){return Ih.call(i,b,this.X)};o.Z=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,a,b,i);case 3:return Ih.call(i,b,this.X,this.X[b],d)}c("Invalid arity: "+arguments.length)}}();Ye.call(i);
function Kh(a,b){return new Jh(i,a,b)}Jh.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,this,b);case 3:return J.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Lh(a,b,d){this.d=a;this.count=b;this.C=d}o=Lh.prototype;o.o=function(a,b){return Gh.call(i,a,b)};o.I=function(a,b){return H(hg.call(i,b))?lf.call(i,a,I.call(i,b,0),I.call(i,b,1)):Bg.call(i,bf,a,b)};
o.A=function(){var a=this;if(H(Qg.call(i,a.count))){var b=jg.call(i,a.C);return wh.call(i,function(b){return oh.call(i,Ch,yh.call(i,2,a.C[b]))},b)}else return i};o.W=!0;o.M=function(a,b){return new Lh(b,this.count,this.C)};o.Cb=!0;o.eb=function(a,b){var d=cg.call(i,b),e=this.C[d],f=H(e)?Hh.call(i,2,b,e):i;if(H(Vf.call(i,f)))return a;else{var g=Ob.call(i,this.C);H(Jg.call(i,3,e.length))?kg.call(i,g,d):(e=Xe.call(i,e),e.splice(f,2),g[d]=e);return new Lh(this.d,Kg.call(i,this.count),g)}};o.K=!0;
o.L=l("d");o.J=function(a){return Xg.call(i,a)};o.Y=l("count");o.Ja=function(a,b,d){var a=cg.call(i,b),e=this.C[a];if(H(e)){var e=Xe.call(i,e),f=Ob.call(i,this.C);f[a]=e;a=Hh.call(i,2,b,e);return H(a)?(e[O.call(i,a)]=d,new Lh(this.d,this.count,f)):(e.push(b,d),new Lh(this.d,O.call(i,this.count),f))}else return e=Ob.call(i,this.C),e[a]=Ye.call(i,b,d),new Lh(this.d,O.call(i,this.count),e)};o.cb=function(a,b){var d=this.C[cg.call(i,b)],d=H(d)?Hh.call(i,2,b,d):i;return H(d)?!0:!1};
o.Z=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,a,b,i);case 3:var e=this.C[cg.call(i,b)],f=H(e)?Hh.call(i,2,b,e):i;return H(f)?e[O.call(i,f)]:d}c("Invalid arity: "+arguments.length)}}();var Mh=new Lh(i,0,ig.call(i));function Nh(a,b){for(var d=a.length,e=0,f=Mh;;)if(H(Hg.call(i,e,d)))var g=O.call(i,e),f=Yf.call(i,f,a[e],b[e]),e=g;else return f}
Lh.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,this,b);case 3:return J.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Nf(a){for(var b=P(Array.prototype.slice.call(arguments,0),0),b=Q.call(i,b),d=Mh;;)if(H(b))var e=Uf.call(i,b),d=Yf.call(i,d,S.call(i,b),Tf.call(i,b)),b=e;else return d}function Oh(a){return Q.call(i,oh.call(i,S,a))}
function Ph(a){var b=P(Array.prototype.slice.call(arguments,0),0);return H(kh.call(i,nh,b))?Bg.call(i,function(a,b){return V.call(i,H(a)?a:Kh([],{}),b)},b):i}function Qh(a,b){this.d=a;this.Ca=b}o=Qh.prototype;o.wc=!0;o.Db=function(a,b){return new Qh(this.d,Zf.call(i,this.Ca,b))};o.o=function(a,b){var d=eg.call(i,b);return H(d)?(d=K.call(i,Wf.call(i,a),Wf.call(i,b)),H(d)?jh.call(i,function(b){return vg.call(i,a,b)},b):d):d};o.I=function(a,b){return new Qh(this.d,Yf.call(i,this.Ca,b,i))};
o.A=function(){return Oh.call(i,this.Ca)};o.W=!0;o.M=function(a,b){return new Qh(b,this.Ca)};o.K=!0;o.L=l("d");o.J=function(a){return Xg.call(i,a)};o.Y=function(a){return Wf.call(i,Q.call(i,a))};o.Z=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,a,b,i);case 3:return H(jf.call(i,this.Ca,b))?b:d}c("Invalid arity: "+arguments.length)}}();var Rh=new Qh(i,Nf.call(i));
Qh.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,this,b);case 3:return J.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Sh(a){for(var a=Q.call(i,a),b=Rh;;)if(H(Vf.call(i,dg.call(i,a))))var d=T.call(i,a),b=V.call(i,b,S.call(i,a)),a=d;else return b}
function Th(a){if(H(qg.call(i,a)))return a;else if(H(function(){var b=rg.call(i,a);return H(b)?b:sg.call(i,a)}())){var b=a.lastIndexOf("/");return H(Hg.call(i,b,0))?Tg.call(i,a,2):Tg.call(i,a,O.call(i,b))}else return i}function Uh(a){if(H(function(){var b=rg.call(i,a);return H(b)?b:sg.call(i,a)}())){var b=a.lastIndexOf("/");return H(Jg.call(i,b,-1))?Tg.call(i,a,2,b):i}else return"\ufdd0'else"}
function Vh(a,b){var d=a.exec(b);return H(K.call(i,S.call(i,d),b))?H(K.call(i,Wf.call(i,d),1))?S.call(i,d):Ch.call(i,d):i}function Wh(a,b){var d=a.exec(b);return H(L.call(i,d))?i:H(K.call(i,Wf.call(i,d),1))?S.call(i,d):Ch.call(i,d)}function Xh(a){return new r.RegExp(a)}function Yh(a,b,d,e,f,g){return fh.call(i,Bh([b]),vh.call(i,uh.call(i,Bh([d]),oh.call(i,function(b){return a.call(i,b,f)},g))),Bh([e]))}
var $h=function Zh(b,d){return H(L.call(i,b))?N.call(i,"nil"):H(mg.call(i,b))?N.call(i,"#<undefined>"):H("\ufdd0'else")?fh.call(i,H(function(){var e=Xf.call(i,d,"\ufdd0'meta");return H(e)?(e=H(H(b)?b.K:b)?!0:We.call(i,vf,b),H(e)?ag.call(i,b):e):e}())?fh.call(i,Bh(["^"]),Zh.call(i,ag.call(i,b),d),Bh([" "])):i,H(H(H(b)?b.z:b)?!0:We.call(i,Jf,b))?Lf.call(i,b,d):N.call(i,"#<",X.call(i,b),">")):i};Lh.prototype.z=!0;
Lh.prototype.s=function(a,b){return Yh.call(i,function(a){return Yh.call(i,$h,""," ","",b,a)},"{",", ","}",b,a)};Jf.number=!0;Lf.number=function(a){return N.call(i,X.call(i,a))};Qf.prototype.z=!0;Qf.prototype.s=function(a,b){return Yh.call(i,$h,"("," ",")",b,a)};Z.prototype.z=!0;Z.prototype.s=function(a,b){return Yh.call(i,$h,"("," ",")",b,a)};Jf["boolean"]=!0;Lf["boolean"]=function(a){return N.call(i,X.call(i,a))};Qh.prototype.z=!0;
Qh.prototype.s=function(a,b){return Yh.call(i,$h,"#{"," ","}",b,a)};Jf.string=!0;Lf.string=function(a,b){return H(rg.call(i,a))?N.call(i,X.call(i,":",function(){var b=Uh.call(i,a);return H(b)?X.call(i,b,"/"):i}(),Th.call(i,a))):H(sg.call(i,a))?N.call(i,X.call(i,function(){var b=Uh.call(i,a);return H(b)?X.call(i,b,"/"):i}(),Th.call(i,a))):H("\ufdd0'else")?N.call(i,H("\ufdd0'readably".call(i,b))?Ea.call(i,a):a):i};zh.prototype.z=!0;zh.prototype.s=function(a,b){return Yh.call(i,$h,"["," ","]",b,a)};
Yg.prototype.z=!0;Yg.prototype.s=function(a,b){return Yh.call(i,$h,"("," ",")",b,a)};Jf.array=!0;Lf.array=function(a,b){return Yh.call(i,$h,"#<Array [",", ","]>",b,a)};Zg.prototype.z=!0;Zg.prototype.s=function(){return N.call(i,"()")};ah.prototype.z=!0;ah.prototype.s=function(a,b){return Yh.call(i,$h,"("," ",")",b,a)};Jh.prototype.z=!0;Jh.prototype.s=function(a,b){return Yh.call(i,function(a){return Yh.call(i,$h,""," ","",b,a)},"{",", ","}",b,a)};
function ai(a,b,d){this.state=a;this.d=b;this.qd=d}o=ai.prototype;o.z=!0;o.s=function(a,b){return fh.call(i,Bh(["#<Atom: "]),Lf.call(i,this.state,b),">")};o.K=!0;o.L=l("d");o.vc=l("state");o.o=function(a,b){return Mf.call(i,a,b)};
var bi=function(){function a(a,b){var f=P(Array.prototype.slice.call(arguments,1),0),g=H(og.call(i,f))?hh.call(i,Nf,f):f,f=Xf.call(i,g,"\ufdd0'validator"),g=Xf.call(i,g,"\ufdd0'meta");return new ai(a,g,f)}var b=i,b=function(b,e){switch(arguments.length){case 1:return new ai(b,i,i);default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=1;b.c=function(b){var e=S(b),b=T(b);return a.call(i,e,b)};return b}();
function ci(a,b){var d=a.qd;H(d)&&!H(d.call(i,b))&&c("Validator rejected reference state");return a.state=b}
var di=function(){function a(a,b,f,g,j,k){var n=P(Array.prototype.slice.call(arguments,5),0);return ci.call(i,a,hh.call(i,b,a.state,f,g,j,n))}var b=i,b=function(b,e,f,g,j,k){switch(arguments.length){case 2:return ci.call(i,b,e.call(i,b.state));case 3:return ci.call(i,b,e.call(i,b.state,f));case 4:return ci.call(i,b,e.call(i,b.state,f,g));case 5:return ci.call(i,b,e.call(i,b.state,f,g,j));default:return a.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.e=5;b.c=function(b){var e=S(b),
f=S(U(b)),g=S(U(U(b))),j=S(U(U(U(b)))),k=S(U(U(U(U(b))))),b=T(U(U(U(U(b)))));return a.call(i,e,f,g,j,k,b)};return b}();function ei(a){return uf.call(i,a)};var fi=function(){return function(a,b,d){switch(arguments.length){case 2:return Ch.call(i,X.call(i,a).split(b));case 3:var e;a:if(H(Hg.call(i,d,1)))e=Ch.call(i,X.call(i,a).split(b));else for(var f=a,g=d,j=Bh([]);;)if(H(K.call(i,g,1))){e=V.call(i,j,f);break a}else{var k=Wh.call(i,b,f);if(H(k))var n=k,k=f.indexOf(n),n=f.substring(Dg.call(i,k,Wf.call(i,n))),g=Kg.call(i,g),j=V.call(i,j,f.substring(0,k)),f=n;else{e=V.call(i,j,f);break a}}return e}c("Invalid arity: "+arguments.length)}}();var $=function gi(b){return H(H(b)?b.Eb:b)?b.Eb():function(){var d=gi[s.call(i,b)];return H(d)?d:gi._}().call(i,b)},ii=function hi(b,d){return H(H(b)?b.Fb:b)?b.Fb(0,d):function(){var d=hi[s.call(i,b)];return H(d)?d:hi._}().call(i,b,d)};function ji(a,b,d){this.kd=a;this.Xb=b;this.Ia=d}ji.prototype.Eb=function(){if(H(dg.call(i,ei.call(i,this.Ia)))){var a=ei.call(i,this.Xb);di.call(i,this.Xb,O);return W.call(i,this.kd,a)}else return a=ei.call(i,this.Ia),di.call(i,this.Ia,T),S.call(i,a)};
ji.prototype.Fb=function(a,b){return di.call(i,this.Ia,function(a){return Y.call(i,b,a)})};function ki(a){return new ji(a,bi.call(i,0),bi.call(i,i))}function li(a){var b=sa.call(i,a);return H(b)?b:K.call(i,",",a)}function mi(a){return ta.call(i,a)}function ni(a){return K.call(i,";",a)}function oi(a,b){var d=mi.call(i,b);return H(d)?d:(d=function(){var a=K.call(i,"+",b);return H(a)?a:K.call(i,"-",b)}(),H(d)?mi.call(i,function(){var b=$.call(i,a);ii.call(i,b);return b}()):d)}
var pi=function(){function a(a,d){var e=i;d!==h&&(e=P(Array.prototype.slice.call(arguments,1),0));c(hh.call(i,X,e))}a.e=1;a.c=function(a){S(a);a=T(a);c(hh.call(i,X,a))};return a}();function qi(a){var b=ih.call(i,a,"#");return H(b)?(b=ih.call(i,a,"'"),H(b)?vg.call(i,ri,a):b):b}function si(a,b){for(var d=new Sa(b),e=$.call(i,a);;)if(H(function(){var a=L.call(i,e);return H(a)?a:(a=li.call(i,e),H(a)?a:qi.call(i,e))}()))return ii.call(i,a,e),d.toString();else{d.append(e);var f=$.call(i,a),e=f}}
var ti=Xh.call(i,"([-+]?)(?:(0)|([1-9][0-9]*)|0[xX]([0-9A-Fa-f]+)|0([0-7]+)|([1-9][0-9]?)[rR]([0-9A-Za-z]+)|0[0-9]+)(N)?"),ui=Xh.call(i,"([-+]?[0-9]+)/([0-9]+)"),vi=Xh.call(i,"([-+]?[0-9]+(\\.[0-9]*)?([eE][-+]?[0-9]+)?)(M)?");
function wi(a){var b=Wh.call(i,ti,a);if(H(W.call(i,b,2)))return 0;else{var a=H(K.call(i,"-",W.call(i,b,1)))?-1:1,d=H(W.call(i,b,3))?Bh([W.call(i,b,3),10]):H(W.call(i,b,4))?Bh([W.call(i,b,4),16]):H(W.call(i,b,5))?Bh([W.call(i,b,5),8]):H(W.call(i,b,7))?Bh([W.call(i,b,7),r.parseInt.call(i,W.call(i,b,7))]):H("\ufdd0'default")?Bh([i,i]):i,b=W.call(i,d,0,i),d=W.call(i,d,1,i);return H(L.call(i,b))?i:Fg.call(i,a,r.parseInt.call(i,b,d))}}
function xi(a){var b=Wh.call(i,ui,a),a=W.call(i,b,1),b=W.call(i,b,2);return Gg.call(i,r.parseInt.call(i,a),r.parseInt.call(i,b))}function yi(a){return r.parseFloat.call(i,a)}function zi(a){return H(Vh.call(i,ti,a))?wi.call(i,a):H(Vh.call(i,ui,a))?xi.call(i,a):H(Vh.call(i,vi,a))?yi.call(i,a):i}var Ai=Nh(["t","r","n","\\",'"',"b","f"],["\t","\r","\n","\\",'"',"\u0008","\u000c"]);function Bi(a){return pi.call(i,a,"Unicode characters not supported by reader (yet)")}
function Ci(a,b){var d=$.call(i,b),e=Xf.call(i,Ai,d);return H(e)?e:H(function(){var a=K.call(i,"u",d);return H(a)?a:mi.call(i,d)}())?Bi.call(i,b):pi.call(i,b,"Unsupported escape charater: \\",d)}function Di(a,b){for(var d=$.call(i,b);;)if(H(a.call(i,d)))d=$.call(i,b);else return d}
function Ei(a,b){for(var d=Bh([]);;){var e=Di.call(i,li,b);H(e)||pi.call(i,b,"EOF");if(H(K.call(i,a,e)))return d;else{var f=Xf.call(i,ri,e);H(f)?e=f.call(i,b,e):(ii.call(i,b,e),e=Fi.call(i,b,!0,i));d=H(K.call(i,e,b))?d:V.call(i,d,e)}}}function Gi(a,b){return pi.call(i,a,"Reader for ",b," not implemented yet")}function Hi(a,b){return pi.call(i,a,"Unmached delimiter ",b)}
function Ii(a){for(;;){var b=$.call(i,a);if(H(function(){var a=K.call(i,b,"n");return H(a)?a:(a=K.call(i,b,"r"),H(a)?a:L.call(i,b))}()))return a}}function Ji(a,b){for(var d=new Sa(b),e=$.call(i,a);;)if(H(function(){var a=L.call(i,e);return H(a)?a:(a=li.call(i,e),H(a)?a:vg.call(i,ri,e))}())){ii.call(i,a,e);var f=d.toString(),d=zi.call(i,f);return H(d)?d:pi.call(i,a,"Invalid number format [",f,"]")}else d.append(e),e=f=$.call(i,a)}
function Ki(a){for(var b=new Sa,d=$.call(i,a);;)if(H(L.call(i,d)))return pi.call(i,a,"EOF while reading string");else if(H(K.call(i,"\\",d)))b=Ci.call(i,0,a),d=$.call(i,a);else if(H(K.call(i,'"',d)))return b.toString();else if(H("\ufdd0'default"))b.append(d),d=$.call(i,a);else return i}function Li(a,b){var d=si.call(i,a,b);return H(Fa.call(i,d,"/"))?Ug.call(i,Tg.call(i,d,0,d.indexOf("/")),Tg.call(i,O.call(i,d.indexOf("/")),d.length)):Ug.call(i,d)}
function Mi(a){return H(sg.call(i,a))?Kh(["\ufdd0'tag"],{"\ufdd0'tag":a}):H(qg.call(i,a))?Kh(["\ufdd0'tag"],{"\ufdd0'tag":a}):H(rg.call(i,a))?Nh([a],[!0]):H("\ufdd0'else")?a:i}function Ni(a){return function(b){return N.call(i,a,Fi.call(i,b,!0,i))}}
var ri=Nh(["@","`",'"',"#","%","'","(",")",":",";","[","{","\\","]","}","^","~"],[Ni.call(i,"\ufdd1'deref"),Gi,Ki,function(a,b){var d=$.call(i,a),e=Xf.call(i,Oi,d);return H(e)?e.call(i,a,b):pi.call(i,a,"No dispatch macro for ",d)},Gi,Ni.call(i,"\ufdd1'quote"),function(a){return hh.call(i,N,Ei.call(i,")",a))},Hi,function(a){a=si.call(i,a,$.call(i,a));return H(Fa.call(i,a,"/"))?Vg.call(i,Tg.call(i,a,0,a.indexOf("/")),Tg.call(i,O.call(i,a.indexOf("/")),a.length)):Vg.call(i,a)},Gi,function(a){return Ei.call(i,
"]",a)},function(a){var b=Ei.call(i,"}",a);H(mh.call(i,Wf.call(i,b)))&&pi.call(i,a,"Map literal must contain an even number of forms");return hh.call(i,Nf,b)},$,Hi,Hi,function(a){var b=Mi.call(i,Fi.call(i,a,!0,i));H(gg.call(i,b))||pi.call(i,a,"Metadata must be Symbol,Keyword,String or Map");var d=Fi.call(i,a,!0,i);return H(H(H(d)?d.W:d)?!0:We.call(i,yf,d))?$f.call(i,d,Ph.call(i,ag.call(i,d),b)):pi.call(i,a,"Metadata can only be applied to IWithMetas")},Gi]),Oi=Kh(["{","<",'"',"!","_"],{"{":function(a){return Sh.call(i,
Ei.call(i,"}",a))},"<":function(a){return function(b){return pi.call(i,b,a)}}.call(i,"Unreadable form"),'"':function(a,b){return Xh.call(i,Ki.call(i,a,b))},"!":Ii,_:function(a){Fi.call(i,a,!0,i);return a}});
function Fi(a,b,d){for(;;){var e=$.call(i,a);if(H(L.call(i,e)))return H(b)?pi.call(i,a,"EOF"):d;else if(!H(li.call(i,e)))if(H(ni.call(i,e)))a=Ii.call(i,a);else if(H("\ufdd0'else")){if(e=H(ri.call(i,e))?ri.call(i,e).call(i,a,e):H(oi.call(i,a,e))?Ji.call(i,a,e):H("\ufdd0'else")?Li.call(i,a,e):i,!H(K.call(i,e,a)))return e}else return i}}Ki=function(a){a=ki.call(i,a);return Fi.call(i,a,!0,i)};function Pi(a,b){return Be.call(i,Th.call(i,a)).info(b)}function Qi(a,b){Be.call(i,Th.call(i,a)).log(we,b,h)}function Ri(a,b){Be.call(i,Th.call(i,a)).log(ze,b,h)}function Si(a){a=new Ie(Sb.call(i,a));He.call(i).wb(Ae);if(!0!=a.Zb){var b=He(),d=a.gd;if(!b.Ba)b.Ba=[];b.Ba.push(d);a.Zb=!0}};function Ti(){return new Je}
var Ui=function(){function a(a,b,f,g,j){var k=new ld;G(k,a,Oe,b);G(k,a,Ne,function(a){var a=a.message,b=Vh.call(i,/\/([^ ]+) (.*)/,a);W.call(i,b,0,i);var d=W.call(i,b,1,i),b=W.call(i,b,2,i);Ri.call(i,"websocket",X.call(i,"R: ",a));return f.call(i,d,b)});H(g)&&G(k,a,Me,g);H(j)&&G(k,a,Le,j);return a}var b=i;return b=function(d,e,f,g,j){switch(arguments.length){case 3:return b.call(i,d,e,f,i);case 4:return b.call(i,d,e,f,g,i);case 5:return a.call(this,d,e,f,g,j)}c("Invalid arity: "+arguments.length)}}();
function Vi(a,b){try{return a.open(b),a}catch(d){if(H(ng.call(i,r.Error,d)))return Qi.call(i,"websocket","No WebSocket supported, get a decent browser.");else if(H("\ufdd0'else"))c(d);else return i}}function Wi(a){return a.close}var Xi=function(){var a=i;return a=function(b,d,e){switch(arguments.length){case 2:return a.call(i,b,d,i);case 3:var f=X.call(i,"/",d,H(e)?X.call(i," ",e):i);Ri.call(i,"websocket",X.call(i,"T: ",f));return b.send(f)}c("Invalid arity: "+arguments.length)}}();var Yi=Kh(["\ufdd0'nick","\ufdd0'users"],{"\ufdd0'nick":i,"\ufdd0'users":Sh([])}),Zi=bi.call(i,Yi);function $i(){return"\ufdd0'nick".call(i,ei.call(i,Zi))}function aj(a){di.call(i,Zi,function(b){var e="\ufdd0'users".call(i,b),f="\ufdd0'nick".call(i,b);Ri.call(i,"state",X.call(i,"chnick! ",a," users: ",e));return Yf.call(i,b,"\ufdd0'nick",a,"\ufdd0'users",V.call(i,bg.call(i,e,f),a))});var b=Sb.call(i,"nick");return H(b)?b.textContent=a:i}function bj(){return"\ufdd0'users".call(i,ei.call(i,Zi))}
function cj(a){return di.call(i,Zi,Yf,"\ufdd0'users",a)}function dj(a){return di.call(i,Zi,function(b){return Yf.call(i,b,"\ufdd0'users",V.call(i,"\ufdd0'users".call(i,b),a))})}function ej(a){return di.call(i,Zi,function(b){return Yf.call(i,b,"\ufdd0'users",bg.call(i,"\ufdd0'users".call(i,b),a))})}function fj(a,b){return di.call(i,Zi,function(d){return Yf.call(i,d,"\ufdd0'users",V.call(i,bg.call(i,"\ufdd0'users".call(i,d),a),b))})};var gj=function(){var a=i;return a=function(b,d){switch(arguments.length){case 0:return a.call(i,bj.call(i),$i.call(i));case 2:var e;a:{var f=Sb.call(i,"participants");cc.call(i,f);for(var g=Q.call(i,Ag.call(i,b));;)if(H(g)){var j=S.call(i,g),k=Xb.call(i,"li");Fb.call(i,k,"nick");H(K.call(i,j,d))&&Hb.call(i,k,"me");fc.call(i,k,Th.call(i,j));bc.call(i,f,k);g=U.call(i,g)}else{e=i;break a}}return e}c("Invalid arity: "+arguments.length)}}();
function hj(a){var b=fi.call(i,a,/ /);return H(K.call(i,2,Wf.call(i,b)))?(a=W.call(i,b,0,i),b=W.call(i,b,1,i),H(K.call(i,a,$i.call(i)))?aj.call(i,b):fj.call(i,a,b),gj.call(i)):aj.call(i,a)}function ij(a){var b=Sb.call(i,"messages"),d=ac.call(i,"li");fc.call(i,d,a);return bc.call(i,b,d)}function jj(a){dj.call(i,a);ij.call(i,X.call(i,a," joined"));return gj.call(i)}function kj(a){ej.call(i,a);ij.call(i,X.call(i,a," left"));return gj.call(i)}
function lj(a){return ij.call(i,X.call(i,"#",a," connected"))}function mj(a){a=xh.call(i,Sh([]),oh.call(i,Th,Ki.call(i,a)));return H(a)?(cj.call(i,a),gj.call(i,a,$i.call(i))):i}function nj(a){return Pi.call(i,"websocket",X.call(i,"WebSocket opened: ",a))}
function oj(a,b){H(K.call(i,a,"nick"))?hj.call(i,b):H(K.call(i,a,"msg"))?ij.call(i,b):H(K.call(i,a,"joined"))?jj.call(i,b):H(K.call(i,a,"left"))?kj.call(i,b):H(K.call(i,a,"count"))?lj.call(i,b):H(K.call(i,a,"users"))&&mj.call(i,b);return Ri.call(i,"websocket",X.call(i,a,":",b,": DONE"))}function pj(a){return Pi.call(i,"websocket",X.call(i,"WebSocket error: ",a))}function qj(a){return Pi.call(i,"websocket",X.call(i,"WebSocket closed: ",a))}
function rj(a){return Q.call(i,rh.call(i,1,Vh.call(i,/^\/([^ ]+)(?: )?(.*)$/,a)))}function sj(a){return function(b){var b=b.target,d=b.value,e=rj.call(i,d);H(e)?hh.call(i,Xi,a,e):Xi.call(i,a,"msg",d);return b.value=""}}
function tj(a){var b=Sb.call(i,"msg"),d=new he;if(d.oa)c(Error("Component already rendered"));else if(b){d.pc=!0;if(!d.l||d.l.g!=B(b))d.l=A(b);d.ib(b);d.Na()}else c(Error("Invalid element to decorate"));new Cd(b,b.getAttribute("label"));Pi.call(i,"client",X.call(i,"Installing handler on ",b));F.call(i,b,"change",a);b.focus(!0);return new Ve("log-h","log",!1)}function uj(){var a=Sb.call(i,"msg");a.disabled=!0;return a.ud=!0}
function vj(a){var b=document.body;Pi.call(i,"client","Installing unload hook.");return b.onunload=a}(function(){Si.call(i,"log");Pi.call(i,"client","Initilizing application.");var a=Vi.call(i,Ui.call(i,Ti.call(i),nj,oj,pj,qj),"ws://"+document.location.host+"/socket");return H(a)?(vj.call(i,function(){return Wi.call(i,a).call(i)}),tj.call(i,sj.call(i,a))):(uj.call(i),ij.call(i,"No WebSocket supported, get a decent browser."))}).call(i);
